// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archive.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const archiveExists = `-- name: ArchiveExists :execresult
;

select title
from archive
where title = ?
`

func (q *Queries) ArchiveExists(ctx context.Context, title string) (sql.Result, error) {
	return q.db.ExecContext(ctx, archiveExists, title)
}

const archiveIDExists = `-- name: ArchiveIDExists :execresult
;

select id
from archive
where id = ?
`

func (q *Queries) ArchiveIDExists(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, archiveIDExists, id)
}

const countArchives = `-- name: CountArchives :one
;

select count(*)
from archive
`

func (q *Queries) CountArchives(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArchives)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArchive = `-- name: CreateArchive :one
insert into archive (
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    created_at,
    updated_at,
    release_date
)
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
returning id, title, summary, language, category, page_count, file_path, file_hash, created_at, updated_at, release_date
`

type CreateArchiveParams struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) CreateArchive(ctx context.Context, arg CreateArchiveParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, createArchive,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Language,
		arg.Category,
		arg.PageCount,
		arg.FilePath,
		arg.FileHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ReleaseDate,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const deleteAllArchive = `-- name: DeleteAllArchive :exec
;

delete from archive
`

func (q *Queries) DeleteAllArchive(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllArchive)
	return err
}

const deleteArchive = `-- name: DeleteArchive :exec
delete from archive
where id = ?
`

func (q *Queries) DeleteArchive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArchive, id)
	return err
}

const deleteArchiveByFilePath = `-- name: DeleteArchiveByFilePath :exec
;

delete from archive
where file_path = ?
`

func (q *Queries) DeleteArchiveByFilePath(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, deleteArchiveByFilePath, filePath)
	return err
}

const filePathExists = `-- name: FilePathExists :execresult
;

select file_path
from archive
where file_path = ?
`

func (q *Queries) FilePathExists(ctx context.Context, filePath string) (sql.Result, error) {
	return q.db.ExecContext(ctx, filePathExists, filePath)
}

const getAllArchives = `-- name: GetAllArchives :many
;

select
    archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_hash, archive.created_at, archive.updated_at, archive.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.status
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user
    and reading_progress.user_id = ?1
order by archive.id
`

type GetAllArchivesRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int64     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Status      *string    `json:"status"`
}

func (q *Queries) GetAllArchives(ctx context.Context, uid *string) ([]GetAllArchivesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllArchives, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllArchivesRow
	for rows.Next() {
		var i GetAllArchivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFilePaths = `-- name: GetAllFilePaths :many
;

select id, file_path
from archive
`

type GetAllFilePathsRow struct {
	ID       string `json:"id"`
	FilePath string `json:"file_path"`
}

func (q *Queries) GetAllFilePaths(ctx context.Context) ([]GetAllFilePathsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFilePathsRow
	for rows.Next() {
		var i GetAllFilePathsRow
		if err := rows.Scan(&i.ID, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByFileHash = `-- name: GetArchiveByFileHash :one
;

select id, title, summary, language, category, page_count, file_path, file_hash, created_at, updated_at, release_date
from archive
where file_hash = ?
`

func (q *Queries) GetArchiveByFileHash(ctx context.Context, fileHash string) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveByFileHash, fileHash)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const getArchiveByFilePath = `-- name: GetArchiveByFilePath :one
;

select id, title, summary, language, category, page_count, file_path, file_hash, created_at, updated_at, release_date
from archive
where file_path = ?
`

func (q *Queries) GetArchiveByFilePath(ctx context.Context, filePath string) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveByFilePath, filePath)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const getArchiveByID = `-- name: GetArchiveByID :one
;

select id, title, summary, language, category, page_count, file_path, file_hash, created_at, updated_at, release_date
from archive
where id = ?
`

func (q *Queries) GetArchiveByID(ctx context.Context, id string) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveByID, id)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const getArchiveList = `-- name: GetArchiveList :many
;

select
    archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_hash, archive.created_at, archive.updated_at, archive.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.status
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = ?3
limit ?
offset ?
`

type GetArchiveListParams struct {
	Uid    *string `json:"uid"`
	Limit  int64   `json:"limit"`
	Offset int64   `json:"offset"`
}

type GetArchiveListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int64     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Status      *string    `json:"status"`
}

func (q *Queries) GetArchiveList(ctx context.Context, arg GetArchiveListParams) ([]GetArchiveListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveList, arg.Uid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveListRow
	for rows.Next() {
		var i GetArchiveListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveShuffle = `-- name: GetArchiveShuffle :one
;

select id
from archive
limit ?
offset ?
`

type GetArchiveShuffleParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetArchiveShuffle(ctx context.Context, arg GetArchiveShuffleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getArchiveShuffle, arg.Limit, arg.Offset)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getFilePathByID = `-- name: GetFilePathByID :one
;

select file_path
from archive
where id = ?
`

func (q *Queries) GetFilePathByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getFilePathByID, id)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const getRecentlyReadArchives = `-- name: GetRecentlyReadArchives :many
;

select
    archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_hash, archive.created_at, archive.updated_at, archive.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.status
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = ?1
where reading_progress.last_read is not null
order by reading_progress.last_read
`

type GetRecentlyReadArchivesRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int64     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Status      *string    `json:"status"`
}

func (q *Queries) GetRecentlyReadArchives(ctx context.Context, uid *string) ([]GetRecentlyReadArchivesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentlyReadArchives, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyReadArchivesRow
	for rows.Next() {
		var i GetRecentlyReadArchivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArchive = `-- name: UpdateArchive :one
;

update archive
set title = coalesce(?3, title),
    summary = coalesce(?4, summary),
    language = coalesce(slqc.narg('language'), language),
    category = coalesce(?5, category),
    updated_at = coalesce(?, updated_at),
    release_date = coalesce(?6, release_date)
where id = ?
returning id, title, summary, language, category, page_count, file_path, file_hash, created_at, updated_at, release_date
`

type UpdateArchiveParams struct {
	Title       *string    `json:"title"`
	Summary     *string    `json:"summary"`
	Category    *string    `json:"category"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	ID          string     `json:"id"`
}

func (q *Queries) UpdateArchive(ctx context.Context, arg UpdateArchiveParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, updateArchive,
		arg.Title,
		arg.Summary,
		arg.Category,
		arg.UpdatedAt,
		arg.ReleaseDate,
		arg.ID,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const updateFileHash = `-- name: UpdateFileHash :exec
update archive
set file_hash = ?,
    updated_at = ?
where id = ?
`

type UpdateFileHashParams struct {
	FileHash  string    `json:"file_hash"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateFileHash(ctx context.Context, arg UpdateFileHashParams) error {
	_, err := q.db.ExecContext(ctx, updateFileHash, arg.FileHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateFilePath = `-- name: UpdateFilePath :exec
;

update archive
set file_path = ?,
    updated_at = ?
where id = ?
`

type UpdateFilePathParams struct {
	FilePath  string    `json:"file_path"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateFilePath(ctx context.Context, arg UpdateFilePathParams) error {
	_, err := q.db.ExecContext(ctx, updateFilePath, arg.FilePath, arg.UpdatedAt, arg.ID)
	return err
}
