# Generate migrations
generate:
	@echo "Generating migrations..."
	@npx drizzle-kit generate

# Run migrations
migrate:
	@echo "Running migrations..."
	@npx drizzle-kit migrate

# Start dev server
dev:
	@pnpm dev -o --host

.PHONY: generate migrate dev
