// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: archive.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const archiveExists = `-- name: ArchiveExists :execresult
select title
from archives
where title = $1
`

func (q *Queries) ArchiveExists(ctx context.Context, title string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, archiveExists, title)
}

const archiveIDExists = `-- name: ArchiveIDExists :execresult
select archive_id
from archives
where archive_id = $1
`

func (q *Queries) ArchiveIDExists(ctx context.Context, archiveID string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, archiveIDExists, archiveID)
}

const countArchives = `-- name: CountArchives :one
select count(*)
from archives
`

func (q *Queries) CountArchives(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArchives)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArchive = `-- name: CreateArchive :one
insert into archives (
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    archive_id,
    hash,
    thumbs_path,
    cover_path,
    type,
    created_at,
    updated_at,
    release_date
    )
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
returning
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    archive_id,
    hash,
    thumbs_path,
    cover_path,
    type,
    created_at,
    updated_at,
    release_date
`

type CreateArchiveParams struct {
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

type CreateArchiveRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) CreateArchive(ctx context.Context, arg CreateArchiveParams) (CreateArchiveRow, error) {
	row := q.db.QueryRow(ctx, createArchive,
		arg.Title,
		arg.Summary,
		arg.Language,
		arg.Category,
		arg.PageCount,
		arg.FilePath,
		arg.ArchiveID,
		arg.Hash,
		arg.ThumbsPath,
		arg.CoverPath,
		arg.Type,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ReleaseDate,
	)
	var i CreateArchiveRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.ArchiveID,
		&i.Hash,
		&i.ThumbsPath,
		&i.CoverPath,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const deleteArchive = `-- name: DeleteArchive :exec
delete from archives
where archive_id = $1
`

func (q *Queries) DeleteArchive(ctx context.Context, archiveID string) error {
	_, err := q.db.Exec(ctx, deleteArchive, archiveID)
	return err
}

const filePathExists = `-- name: FilePathExists :execresult
select file_path
from archives
where file_path = $1
`

func (q *Queries) FilePathExists(ctx context.Context, filePath *string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, filePathExists, filePath)
}

const getAllArchives = `-- name: GetAllArchives :many
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    archive_id,
    hash,
    thumbs_path,
    cover_path,
    type,
    created_at,
    updated_at,
    release_date
from archives
order by archive_id
`

type GetAllArchivesRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetAllArchives(ctx context.Context) ([]GetAllArchivesRow, error) {
	rows, err := q.db.Query(ctx, getAllArchives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllArchivesRow
	for rows.Next() {
		var i GetAllArchivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByFilePath = `-- name: GetArchiveByFilePath :one
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    archive_id,
    hash,
    thumbs_path,
    cover_path,
    type,
    created_at,
    updated_at,
    release_date
from archives
where file_path = $1
`

type GetArchiveByFilePathRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchiveByFilePath(ctx context.Context, filePath *string) (GetArchiveByFilePathRow, error) {
	row := q.db.QueryRow(ctx, getArchiveByFilePath, filePath)
	var i GetArchiveByFilePathRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.ArchiveID,
		&i.Hash,
		&i.ThumbsPath,
		&i.CoverPath,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const getArchiveByID = `-- name: GetArchiveByID :one
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    archive_id,
    hash,
    thumbs_path,
    cover_path,
    type,
    created_at,
    updated_at,
    release_date
from archives
where archive_id = $1
`

type GetArchiveByIDRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchiveByID(ctx context.Context, archiveID string) (GetArchiveByIDRow, error) {
	row := q.db.QueryRow(ctx, getArchiveByID, archiveID)
	var i GetArchiveByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.ArchiveID,
		&i.Hash,
		&i.ThumbsPath,
		&i.CoverPath,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const getArchiveList = `-- name: GetArchiveList :many
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    archive_id,
    hash,
    thumbs_path,
    cover_path,
    type,
    created_at,
    updated_at,
    release_date
from archives
limit $1
offset $2
`

type GetArchiveListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetArchiveListRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchiveList(ctx context.Context, arg GetArchiveListParams) ([]GetArchiveListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveListRow
	for rows.Next() {
		var i GetArchiveListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastArchiveID = `-- name: GetLastArchiveID :one
select archive_id
from archives
order by archive_id desc
limit 1
`

func (q *Queries) GetLastArchiveID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getLastArchiveID)
	var archive_id string
	err := row.Scan(&archive_id)
	return archive_id, err
}

const searchArchives = `-- name: SearchArchives :many
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    archive_id,
    hash,
    thumbs_path,
    cover_path,
    type,
    created_at,
    updated_at,
    release_date,
    ts_rank_cd(search_vector, query) as rank
from archives, websearch_to_tsquery('english', $1) query
where search_vector @@ query
order by rank desc
`

type SearchArchivesRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Rank        float32    `json:"rank"`
}

func (q *Queries) SearchArchives(ctx context.Context, websearchToTsquery string) ([]SearchArchivesRow, error) {
	rows, err := q.db.Query(ctx, searchArchives, websearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArchivesRow
	for rows.Next() {
		var i SearchArchivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const thumbsPathExistsForFilePath = `-- name: ThumbsPathExistsForFilePath :execresult
select thumbs_path
from archives
where file_path = $1
`

func (q *Queries) ThumbsPathExistsForFilePath(ctx context.Context, filePath *string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, thumbsPathExistsForFilePath, filePath)
}

const updateArchive = `-- name: UpdateArchive :one
update archives
set title = coalesce($3, title),
    summary = coalesce($4, summary),
    language = coalesce($5, language),
    category = coalesce($6, category),
    updated_at = coalesce($1, updated_at),
    release_date = coalesce($7, release_date)
where archive_id = $2
returning
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    archive_id,
    hash,
    thumbs_path,
    cover_path,
    type,
    created_at,
    updated_at,
    release_date
`

type UpdateArchiveParams struct {
	UpdatedAt   time.Time  `json:"updated_at"`
	ArchiveID   string     `json:"archive_id"`
	Title       *string    `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	ReleaseDate *time.Time `json:"release_date"`
}

type UpdateArchiveRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) UpdateArchive(ctx context.Context, arg UpdateArchiveParams) (UpdateArchiveRow, error) {
	row := q.db.QueryRow(ctx, updateArchive,
		arg.UpdatedAt,
		arg.ArchiveID,
		arg.Title,
		arg.Summary,
		arg.Language,
		arg.Category,
		arg.ReleaseDate,
	)
	var i UpdateArchiveRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.ArchiveID,
		&i.Hash,
		&i.ThumbsPath,
		&i.CoverPath,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const updateCoverPath = `-- name: UpdateCoverPath :exec
update archives
set cover_path = $1
where archive_id = $2
`

type UpdateCoverPathParams struct {
	CoverPath *string `json:"cover_path"`
	ArchiveID string  `json:"archive_id"`
}

func (q *Queries) UpdateCoverPath(ctx context.Context, arg UpdateCoverPathParams) error {
	_, err := q.db.Exec(ctx, updateCoverPath, arg.CoverPath, arg.ArchiveID)
	return err
}

const updateThumbPath = `-- name: UpdateThumbPath :exec
update archives
set thumbs_path = $1
where archive_id = $2
`

type UpdateThumbPathParams struct {
	ThumbsPath *string `json:"thumbs_path"`
	ArchiveID  string  `json:"archive_id"`
}

func (q *Queries) UpdateThumbPath(ctx context.Context, arg UpdateThumbPathParams) error {
	_, err := q.db.Exec(ctx, updateThumbPath, arg.ThumbsPath, arg.ArchiveID)
	return err
}
