// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: archive.sql

package repository

import (
	"context"
	"time"
)

const createArchive = `-- name: CreateArchive :one
insert into archives (
    title,
    summary,
    lang,
    category,
    page_count,
    file_path,
    a_id,
    created_at,
    updated_at
    )
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, title, summary, lang, category, page_count, file_path, a_id, created_at, updated_at
`

type CreateArchiveParams struct {
	Title     string    `json:"title"`
	Summary   *string   `json:"summary"`
	Lang      *string   `json:"lang"`
	Category  *string   `json:"category"`
	PageCount int64     `json:"page_count"`
	FilePath  *string   `json:"file_path"`
	AID       int64     `json:"a_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateArchive(ctx context.Context, arg CreateArchiveParams) (Archive, error) {
	row := q.db.QueryRow(ctx, createArchive,
		arg.Title,
		arg.Summary,
		arg.Lang,
		arg.Category,
		arg.PageCount,
		arg.FilePath,
		arg.AID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Lang,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.AID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllArchives = `-- name: GetAllArchives :many
select id, title, summary, lang, category, page_count, file_path, a_id, created_at, updated_at
from archives
order by a_id
`

func (q *Queries) GetAllArchives(ctx context.Context) ([]Archive, error) {
	rows, err := q.db.Query(ctx, getAllArchives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Lang,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.AID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByAID = `-- name: GetArchiveByAID :one
select id, title, summary, lang, category, page_count, file_path, a_id, created_at, updated_at
from archives
where a_id = $1
`

func (q *Queries) GetArchiveByAID(ctx context.Context, aID int64) (Archive, error) {
	row := q.db.QueryRow(ctx, getArchiveByAID, aID)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Lang,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.AID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArchiveLastAID = `-- name: GetArchiveLastAID :one
select a_id
from archives
order by a_id desc
limit 1
`

func (q *Queries) GetArchiveLastAID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getArchiveLastAID)
	var a_id int64
	err := row.Scan(&a_id)
	return a_id, err
}
