// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: artist.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const addArtistToArchive = `-- name: AddArtistToArchive :exec
insert into archives_artists (archive_id, artist_id)
values ($1, $2)
`

type AddArtistToArchiveParams struct {
	ArchiveID int64 `json:"archive_id"`
	ArtistID  int64 `json:"artist_id"`
}

func (q *Queries) AddArtistToArchive(ctx context.Context, arg AddArtistToArchiveParams) error {
	_, err := q.db.Exec(ctx, addArtistToArchive, arg.ArchiveID, arg.ArtistID)
	return err
}

const addArtistToGroup = `-- name: AddArtistToGroup :exec
insert into artists_groups (artist_id, group_id)
values ($1, $2)
`

type AddArtistToGroupParams struct {
	ArtistID int64 `json:"artist_id"`
	GroupID  int64 `json:"group_id"`
}

func (q *Queries) AddArtistToGroup(ctx context.Context, arg AddArtistToGroupParams) error {
	_, err := q.db.Exec(ctx, addArtistToGroup, arg.ArtistID, arg.GroupID)
	return err
}

const artistAliasExists = `-- name: ArtistAliasExists :execresult
select alias
from artist_aliases
where alias = $1
`

func (q *Queries) ArtistAliasExists(ctx context.Context, alias string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, artistAliasExists, alias)
}

const artistExists = `-- name: ArtistExists :execresult
select name
from artists
where name = $1
`

func (q *Queries) ArtistExists(ctx context.Context, name string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, artistExists, name)
}

const artistLinkExists = `-- name: ArtistLinkExists :execresult
select link
from artist_links
where link = $1
`

func (q *Queries) ArtistLinkExists(ctx context.Context, link string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, artistLinkExists, link)
}

const createAlias = `-- name: CreateAlias :exec
insert into artist_aliases (alias, artist_id)
values ($1, $2)
`

type CreateAliasParams struct {
	Alias    string `json:"alias"`
	ArtistID int64  `json:"artist_id"`
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) error {
	_, err := q.db.Exec(ctx, createAlias, arg.Alias, arg.ArtistID)
	return err
}

const createArtist = `-- name: CreateArtist :one
insert into artists (name, count, created_at, updated_at)
values ($1, $2, $3, $4)
returning id, name, count, created_at, updated_at
`

type CreateArtistParams struct {
	Name      string    `json:"name"`
	Count     int64     `json:"count"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist,
		arg.Name,
		arg.Count,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createArtistLink = `-- name: CreateArtistLink :exec
insert into artist_links (link, artist_id)
values ($1, $2)
`

type CreateArtistLinkParams struct {
	Link     string `json:"link"`
	ArtistID int64  `json:"artist_id"`
}

func (q *Queries) CreateArtistLink(ctx context.Context, arg CreateArtistLinkParams) error {
	_, err := q.db.Exec(ctx, createArtistLink, arg.Link, arg.ArtistID)
	return err
}

const deleteArtist = `-- name: DeleteArtist :exec
delete from artists
where id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const getAllArtists = `-- name: GetAllArtists :many
select id, name, count, created_at, updated_at
from artists
order by id
`

func (q *Queries) GetAllArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getAllArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveArtists = `-- name: GetArchiveArtists :many
select artists.id, artists.name, artists.count, artists.created_at, artists.updated_at
from archives
join archives_artists on archives.id = archives_artists.archive_id
join artists on archives_artists.artist_id = artists.id
where archives.archive_id = $1
`

func (q *Queries) GetArchiveArtists(ctx context.Context, archiveID string) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArchiveArtists, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByArtist = `-- name: GetArchiveIDsByArtist :many
select archives.archive_id
from archives
join archives_artists on archives.id = archives_artists.archive_id
join artists on archives_artists.artist_id = artists.id
where artists.name = $1
`

func (q *Queries) GetArchiveIDsByArtist(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByArtist, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var archive_id string
		if err := rows.Scan(&archive_id); err != nil {
			return nil, err
		}
		items = append(items, archive_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByArtist = `-- name: GetArchivesByArtist :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date
from archives
join archives_artists on archives.id = archives_artists.archive_id
join artists on archives_artists.artist_id = artists.id
where artists.name = $1
`

type GetArchivesByArtistRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchivesByArtist(ctx context.Context, name string) ([]GetArchivesByArtistRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByArtist, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByArtistRow
	for rows.Next() {
		var i GetArchivesByArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByArtistList = `-- name: GetArchivesByArtistList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date
from archives
join archives_artists on archives.id = archives_artists.archive_id
join artists on archives_artists.artist_id = artists.id
where artists.name = $1
limit $2
offset $3
`

type GetArchivesByArtistListParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetArchivesByArtistListRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchivesByArtistList(ctx context.Context, arg GetArchivesByArtistListParams) ([]GetArchivesByArtistListRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByArtistList, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByArtistListRow
	for rows.Next() {
		var i GetArchivesByArtistListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistAliases = `-- name: GetArtistAliases :many
select artist_aliases.id, artist_aliases.alias
from artists
join artist_aliases on artists.id = artist_aliases.artist_id
where name = $1
`

type GetArtistAliasesRow struct {
	ID    int64  `json:"id"`
	Alias string `json:"alias"`
}

func (q *Queries) GetArtistAliases(ctx context.Context, name string) ([]GetArtistAliasesRow, error) {
	rows, err := q.db.Query(ctx, getArtistAliases, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistAliasesRow
	for rows.Next() {
		var i GetArtistAliasesRow
		if err := rows.Scan(&i.ID, &i.Alias); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistByName = `-- name: GetArtistByName :one
select id, name, count, created_at, updated_at
from artists
where name = $1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistGroups = `-- name: GetArtistGroups :many
select groups.id, groups.name
from artists
join artists_groups on artists.id = artists_groups.artist_id
join groups on artists_groups.group_id = groups.id
where artists.name = $1
`

type GetArtistGroupsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetArtistGroups(ctx context.Context, name string) ([]GetArtistGroupsRow, error) {
	rows, err := q.db.Query(ctx, getArtistGroups, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistGroupsRow
	for rows.Next() {
		var i GetArtistGroupsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistLinks = `-- name: GetArtistLinks :many
select artist_links.id, artist_links.link
from artists
join artist_links on artists.id = artist_links.artist_id
where name = $1
`

type GetArtistLinksRow struct {
	ID   int64  `json:"id"`
	Link string `json:"link"`
}

func (q *Queries) GetArtistLinks(ctx context.Context, name string) ([]GetArtistLinksRow, error) {
	rows, err := q.db.Query(ctx, getArtistLinks, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistLinksRow
	for rows.Next() {
		var i GetArtistLinksRow
		if err := rows.Scan(&i.ID, &i.Link); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistList = `-- name: GetArtistList :many
select id, name, count, created_at, updated_at
from artists
order by $1
limit $2
offset $3
`

type GetArtistListParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetArtistList(ctx context.Context, arg GetArtistListParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtistList, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArtistAliases = `-- name: RemoveArtistAliases :exec
delete from artist_aliases
where artist_id = $1
`

func (q *Queries) RemoveArtistAliases(ctx context.Context, artistID int64) error {
	_, err := q.db.Exec(ctx, removeArtistAliases, artistID)
	return err
}

const removeArtistFromArchive = `-- name: RemoveArtistFromArchive :many
delete from archives_artists
where archive_id = $1
returning
    artist_id,
    (select artists.count from artists where artists.id = archives_artists.artist_id)
`

type RemoveArtistFromArchiveRow struct {
	ArtistID int64 `json:"artist_id"`
	Count    int64 `json:"count"`
}

func (q *Queries) RemoveArtistFromArchive(ctx context.Context, archiveID int64) ([]RemoveArtistFromArchiveRow, error) {
	rows, err := q.db.Query(ctx, removeArtistFromArchive, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoveArtistFromArchiveRow
	for rows.Next() {
		var i RemoveArtistFromArchiveRow
		if err := rows.Scan(&i.ArtistID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArtistFromGroup = `-- name: RemoveArtistFromGroup :exec
delete from artists_groups
where artist_id = $1
`

func (q *Queries) RemoveArtistFromGroup(ctx context.Context, artistID int64) error {
	_, err := q.db.Exec(ctx, removeArtistFromGroup, artistID)
	return err
}

const removeArtistLinks = `-- name: RemoveArtistLinks :exec
delete from artist_links
where artist_id = $1
`

func (q *Queries) RemoveArtistLinks(ctx context.Context, artistID int64) error {
	_, err := q.db.Exec(ctx, removeArtistLinks, artistID)
	return err
}

const totalArtists = `-- name: TotalArtists :one
select count(id)
from artists
`

func (q *Queries) TotalArtists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalArtists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateArtist = `-- name: UpdateArtist :one
update artists
set name = $1,
    updated_at = $2
where name = $3::text
returning id, name, count, created_at, updated_at
`

type UpdateArtistParams struct {
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
	OldName   string    `json:"old_name"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist, arg.Name, arg.UpdatedAt, arg.OldName)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtistCount = `-- name: UpdateArtistCount :exec
update artists
set count = $1
where id = $2
`

type UpdateArtistCountParams struct {
	Count int64 `json:"count"`
	ID    int64 `json:"id"`
}

func (q *Queries) UpdateArtistCount(ctx context.Context, arg UpdateArtistCountParams) error {
	_, err := q.db.Exec(ctx, updateArtistCount, arg.Count, arg.ID)
	return err
}
