// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: category.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const categoryExists = `-- name: CategoryExists :execresult
select id, title, summary, language, category, page_count, file_path, archive_id, hash, thumbs_path, cover_path, type, created_at, updated_at, release_date
from archives
where category = $1
`

func (q *Queries) CategoryExists(ctx context.Context, category *string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, categoryExists, category)
}

const getAllCategory = `-- name: GetAllCategory :many
select category
from archives
where category is not null
`

func (q *Queries) GetAllCategory(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getAllCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var category *string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByCategory = `-- name: GetArchivesByCategory :many
select id, title, summary, language, category, page_count, file_path, archive_id, hash, thumbs_path, cover_path, type, created_at, updated_at, release_date
from archives
where category = $1
`

func (q *Queries) GetArchivesByCategory(ctx context.Context, category *string) ([]Archive, error) {
	rows, err := q.db.Query(ctx, getArchivesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByCategoryList = `-- name: GetArchivesByCategoryList :many
select id, title, summary, language, category, page_count, file_path, archive_id, hash, thumbs_path, cover_path, type, created_at, updated_at, release_date
from archives
where category = $1
limit $2
offset $3
`

type GetArchivesByCategoryListParams struct {
	Category *string `json:"category"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
}

func (q *Queries) GetArchivesByCategoryList(ctx context.Context, arg GetArchivesByCategoryListParams) ([]Archive, error) {
	rows, err := q.db.Query(ctx, getArchivesByCategoryList, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalArchivesWithCategory = `-- name: TotalArchivesWithCategory :one
select count(archive_id)
from archives
where category = $1
`

func (q *Queries) TotalArchivesWithCategory(ctx context.Context, category *string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchivesWithCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}
