// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const categoryExists = `-- name: CategoryExists :execresult
select category
from archives
where category = $1
`

func (q *Queries) CategoryExists(ctx context.Context, category *string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, categoryExists, category)
}

const getAllCategory = `-- name: GetAllCategory :many
select category
from archives
where category is not null
`

func (q *Queries) GetAllCategory(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getAllCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var category *string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByCategory = `-- name: GetArchiveIDsByCategory :many
select archives.id
from archives
where category = $1
`

func (q *Queries) GetArchiveIDsByCategory(ctx context.Context, category *string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByCategory = `-- name: GetArchivesByCategory :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    -- archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page
from archives
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $2
where category = $1
`

type GetArchivesByCategoryParams struct {
	Category *string   `json:"category"`
	Uid      uuid.UUID `json:"uid"`
}

type GetArchivesByCategoryRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	FileName    *string    `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchivesByCategory(ctx context.Context, arg GetArchivesByCategoryParams) ([]GetArchivesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByCategory, arg.Category, arg.Uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByCategoryRow
	for rows.Next() {
		var i GetArchivesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByCategoryList = `-- name: GetArchivesByCategoryList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    -- archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page
from archives
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $4
where category = $1
limit $2
offset $3
`

type GetArchivesByCategoryListParams struct {
	Category *string   `json:"category"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Uid      uuid.UUID `json:"uid"`
}

type GetArchivesByCategoryListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	FileName    *string    `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchivesByCategoryList(ctx context.Context, arg GetArchivesByCategoryListParams) ([]GetArchivesByCategoryListRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByCategoryList,
		arg.Category,
		arg.Limit,
		arg.Offset,
		arg.Uid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByCategoryListRow
	for rows.Next() {
		var i GetArchivesByCategoryListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalArchivesWithCategory = `-- name: TotalArchivesWithCategory :one
select count(id)
from archives
where category = $1
`

func (q *Queries) TotalArchivesWithCategory(ctx context.Context, category *string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchivesWithCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}
