// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: character.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const addCharacterToArchive = `-- name: AddCharacterToArchive :exec
insert into archives_characters (archive_id, character_id)
values ($1, $2)
`

type AddCharacterToArchiveParams struct {
	ArchiveID   int64 `json:"archive_id"`
	CharacterID int64 `json:"character_id"`
}

func (q *Queries) AddCharacterToArchive(ctx context.Context, arg AddCharacterToArchiveParams) error {
	_, err := q.db.Exec(ctx, addCharacterToArchive, arg.ArchiveID, arg.CharacterID)
	return err
}

const characterExists = `-- name: CharacterExists :execresult
select id, character
from characters
where character = $1
`

func (q *Queries) CharacterExists(ctx context.Context, character string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, characterExists, character)
}

const createCharacter = `-- name: CreateCharacter :one
insert into characters (character)
values ($1)
returning id, character
`

func (q *Queries) CreateCharacter(ctx context.Context, character string) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter, character)
	var i Character
	err := row.Scan(&i.ID, &i.Character)
	return i, err
}

const getAllCharacter = `-- name: GetAllCharacter :many
select id, character
from characters
order by id
`

func (q *Queries) GetAllCharacter(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, getAllCharacter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(&i.ID, &i.Character); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveCharacters = `-- name: GetArchiveCharacters :many
select characters.id, characters.character
from archives
join archives_characters on archives.id = archives_characters.archive_id
join characters on archives_characters.character_id = characters.id
where archives.archive_id = $1
`

func (q *Queries) GetArchiveCharacters(ctx context.Context, archiveID string) ([]Character, error) {
	rows, err := q.db.Query(ctx, getArchiveCharacters, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(&i.ID, &i.Character); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByCharacter = `-- name: GetArchivesByCharacter :many
select archives.archive_id
from archives
join archives_characters on archives.id = archives_characters.archive_id
join characters on archives_characters.character_id = characters.id
where characters.character = $1
`

func (q *Queries) GetArchivesByCharacter(ctx context.Context, character string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchivesByCharacter, character)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var archive_id string
		if err := rows.Scan(&archive_id); err != nil {
			return nil, err
		}
		items = append(items, archive_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacter = `-- name: GetCharacter :one
select id, character
from characters
where character = $1
`

func (q *Queries) GetCharacter(ctx context.Context, character string) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, character)
	var i Character
	err := row.Scan(&i.ID, &i.Character)
	return i, err
}

const removeCharacterFromArchive = `-- name: RemoveCharacterFromArchive :exec
delete from archives_characters
where archive_id = $1
`

func (q *Queries) RemoveCharacterFromArchive(ctx context.Context, archiveID int64) error {
	_, err := q.db.Exec(ctx, removeCharacterFromArchive, archiveID)
	return err
}
