// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: groups.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const createGroup = `-- name: CreateGroup :one
insert into groups (name)
values ($1)
returning id, name
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAllGroups = `-- name: GetAllGroups :many
select id, name
from groups
order by id
`

func (q *Queries) GetAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroup = `-- name: GetGroup :one
select id, name
from groups
where name = $1
`

func (q *Queries) GetGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, name)
	var i Group
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const groupExists = `-- name: GroupExists :execresult
select id, name
from groups
where name = $1
`

func (q *Queries) GroupExists(ctx context.Context, name string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, groupExists, name)
}
