// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: language.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const getAllLanguage = `-- name: GetAllLanguage :many
select language
from archives
where language is not null
`

func (q *Queries) GetAllLanguage(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getAllLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var language *string
		if err := rows.Scan(&language); err != nil {
			return nil, err
		}
		items = append(items, language)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByLanguage = `-- name: GetArchivesByLanguage :many
select id, title, summary, language, category, page_count, file_path, archive_id, hash, thumbs_path, cover_path, type, created_at, updated_at, release_date
from archives
where language = $1
`

func (q *Queries) GetArchivesByLanguage(ctx context.Context, language *string) ([]Archive, error) {
	rows, err := q.db.Query(ctx, getArchivesByLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByLanguageList = `-- name: GetArchivesByLanguageList :many
select id, title, summary, language, category, page_count, file_path, archive_id, hash, thumbs_path, cover_path, type, created_at, updated_at, release_date
from archives
where language = $1
limit $2
offset $3
`

type GetArchivesByLanguageListParams struct {
	Language *string `json:"language"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
}

func (q *Queries) GetArchivesByLanguageList(ctx context.Context, arg GetArchivesByLanguageListParams) ([]Archive, error) {
	rows, err := q.db.Query(ctx, getArchivesByLanguageList, arg.Language, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Archive
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const languageExists = `-- name: LanguageExists :execresult
select id, title, summary, language, category, page_count, file_path, archive_id, hash, thumbs_path, cover_path, type, created_at, updated_at, release_date
from archives
where language = $1
`

func (q *Queries) LanguageExists(ctx context.Context, language *string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, languageExists, language)
}

const totalArchivesWithLanguage = `-- name: TotalArchivesWithLanguage :one
select count(archive_id)
from archives
where language = $1
`

func (q *Queries) TotalArchivesWithLanguage(ctx context.Context, language *string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchivesWithLanguage, language)
	var count int64
	err := row.Scan(&count)
	return count, err
}
