// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: language.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const getAllLanguage = `-- name: GetAllLanguage :many
select language
from archives
where language is not null
`

func (q *Queries) GetAllLanguage(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getAllLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var language *string
		if err := rows.Scan(&language); err != nil {
			return nil, err
		}
		items = append(items, language)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByLanguage = `-- name: GetArchiveIDsByLanguage :many
select archives.archive_id
from archives
where language = $1
`

func (q *Queries) GetArchiveIDsByLanguage(ctx context.Context, language *string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var archive_id string
		if err := rows.Scan(&archive_id); err != nil {
			return nil, err
		}
		items = append(items, archive_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByLanguage = `-- name: GetArchivesByLanguage :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page
from archives
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $2
where language = $1
`

type GetArchivesByLanguageParams struct {
	Language *string   `json:"language"`
	Uid      uuid.UUID `json:"uid"`
}

type GetArchivesByLanguageRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchivesByLanguage(ctx context.Context, arg GetArchivesByLanguageParams) ([]GetArchivesByLanguageRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByLanguage, arg.Language, arg.Uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByLanguageRow
	for rows.Next() {
		var i GetArchivesByLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByLanguageList = `-- name: GetArchivesByLanguageList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page
from archives
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $4
where language = $1
limit $2
offset $3
`

type GetArchivesByLanguageListParams struct {
	Language *string   `json:"language"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Uid      uuid.UUID `json:"uid"`
}

type GetArchivesByLanguageListRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchivesByLanguageList(ctx context.Context, arg GetArchivesByLanguageListParams) ([]GetArchivesByLanguageListRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByLanguageList,
		arg.Language,
		arg.Limit,
		arg.Offset,
		arg.Uid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByLanguageListRow
	for rows.Next() {
		var i GetArchivesByLanguageListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const languageExists = `-- name: LanguageExists :execresult
select language
from archives
where language = $1
`

func (q *Queries) LanguageExists(ctx context.Context, language *string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, languageExists, language)
}

const totalArchivesWithLanguage = `-- name: TotalArchivesWithLanguage :one
select count(archive_id)
from archives
where language = $1
`

func (q *Queries) TotalArchivesWithLanguage(ctx context.Context, language *string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchivesWithLanguage, language)
	var count int64
	err := row.Scan(&count)
	return count, err
}
