// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Archive struct {
	ID           int64       `json:"id"`
	Title        string      `json:"title"`
	Summary      *string     `json:"summary"`
	Language     *string     `json:"language"`
	Category     *string     `json:"category"`
	PageCount    int64       `json:"page_count"`
	FilePath     *string     `json:"file_path"`
	ArchiveID    string      `json:"archive_id"`
	Hash         string      `json:"hash"`
	ThumbsPath   *string     `json:"thumbs_path"`
	CoverPath    *string     `json:"cover_path"`
	Type         string      `json:"type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	ReleaseDate  *time.Time  `json:"release_date"`
	SearchVector interface{} `json:"search_vector"`
}

type ArchivesArtist struct {
	ArchiveID int64 `json:"archive_id"`
	ArtistID  int64 `json:"artist_id"`
}

type ArchivesCharacter struct {
	ArchiveID   int64 `json:"archive_id"`
	CharacterID int64 `json:"character_id"`
}

type ArchivesParody struct {
	ArchiveID int64 `json:"archive_id"`
	ParodyID  int64 `json:"parody_id"`
}

type ArchivesTag struct {
	ArchiveID int64 `json:"archive_id"`
	TagID     int64 `json:"tag_id"`
}

type Artist struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Count     int64     `json:"count"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ArtistAlias struct {
	ID       int64  `json:"id"`
	Alias    string `json:"alias"`
	ArtistID int64  `json:"artist_id"`
}

type ArtistLink struct {
	ID       int64  `json:"id"`
	Link     string `json:"link"`
	ArtistID int64  `json:"artist_id"`
}

type ArtistsGroup struct {
	ArtistID int64 `json:"artist_id"`
	GroupID  int64 `json:"group_id"`
}

type Character struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type Download struct {
	ID              uuid.UUID  `json:"id"`
	Url             string     `json:"url"`
	Filename        string     `json:"filename"`
	Status          string     `json:"status"`
	Progress        *int32     `json:"progress"`
	Error           *string    `json:"error"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	Speed           *int64     `json:"speed"`
	TotalSize       *int64     `json:"total_size"`
	Downloaded      *int64     `json:"downloaded"`
	StartedAt       *time.Time `json:"started_at"`
	CanResume       *bool      `json:"can_resume"`
	ResumeSupported *bool      `json:"resume_supported"`
}

type FavoriteArchive struct {
	ArchiveID   int64     `json:"archive_id"`
	UserID      uuid.UUID `json:"user_id"`
	FavoritedAt time.Time `json:"favorited_at"`
}

type Group struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Parody struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type ReadingProgress struct {
	ArchiveID int64     `json:"archive_id"`
	UserID    uuid.UUID `json:"user_id"`
	Page      int64     `json:"page"`
	State     string    `json:"state"`
	LastRead  time.Time `json:"last_read"`
}

type Session struct {
	SessionID uuid.UUID   `json:"session_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Token     string      `json:"token"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedAt time.Time   `json:"created_at"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent *string     `json:"user_agent"`
}

type Tag struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type Url struct {
	ID        int64  `json:"id"`
	Url       string `json:"url"`
	ArchiveID int64  `json:"archive_id"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
