// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"
)

type Archive struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Summary   *string   `json:"summary"`
	Lang      *string   `json:"lang"`
	Category  *string   `json:"category"`
	PageCount int64     `json:"page_count"`
	FilePath  *string   `json:"file_path"`
	AID       int64     `json:"a_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ArchivesArtist struct {
	ArchiveID int64 `json:"archive_id"`
	ArtistID  int64 `json:"artist_id"`
}

type ArchivesCharacter struct {
	ArchiveID   int64 `json:"archive_id"`
	CharacterID int64 `json:"character_id"`
}

type ArchivesParody struct {
	ArchiveID int64 `json:"archive_id"`
	ParodyID  int64 `json:"parody_id"`
}

type ArchivesTag struct {
	ArchiveID int64 `json:"archive_id"`
	TagID     int64 `json:"tag_id"`
}

type Artist struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ArtistAlias struct {
	ID       int64  `json:"id"`
	Alias    string `json:"alias"`
	ArtistID int64  `json:"artist_id"`
}

type ArtistLink struct {
	ID       int64  `json:"id"`
	Link     string `json:"link"`
	ArtistID int64  `json:"artist_id"`
}

type ArtistsGroup struct {
	ArtistID int64 `json:"artist_id"`
	GroupID  int64 `json:"group_id"`
}

type Character struct {
	ID        int64  `json:"id"`
	Character string `json:"character"`
}

type Group struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Parody struct {
	ID     int64  `json:"id"`
	Parody string `json:"parody"`
}

type Tag struct {
	ID  int64  `json:"id"`
	Tag string `json:"tag"`
}

type Url struct {
	ID        int64  `json:"id"`
	Url       string `json:"url"`
	ArchiveID int64  `json:"archive_id"`
}
