// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type Archive struct {
	ID           int64       `json:"id"`
	Title        string      `json:"title"`
	Summary      *string     `json:"summary"`
	Language     *string     `json:"language"`
	Category     *string     `json:"category"`
	PageCount    int64       `json:"page_count"`
	FilePath     *string     `json:"file_path"`
	ArchiveID    string      `json:"archive_id"`
	Hash         string      `json:"hash"`
	ThumbsPath   *string     `json:"thumbs_path"`
	CoverPath    *string     `json:"cover_path"`
	Type         string      `json:"type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	ReleaseDate  *time.Time  `json:"release_date"`
	SearchVector interface{} `json:"search_vector"`
}

type ArchivesArtist struct {
	ArchiveID int64 `json:"archive_id"`
	ArtistID  int64 `json:"artist_id"`
}

type ArchivesCharacter struct {
	ArchiveID   int64 `json:"archive_id"`
	CharacterID int64 `json:"character_id"`
}

type ArchivesParody struct {
	ArchiveID int64 `json:"archive_id"`
	ParodyID  int64 `json:"parody_id"`
}

type ArchivesTag struct {
	ArchiveID int64 `json:"archive_id"`
	TagID     int64 `json:"tag_id"`
}

type Artist struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Count     int64     `json:"count"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ArtistAlias struct {
	ID       int64  `json:"id"`
	Alias    string `json:"alias"`
	ArtistID int64  `json:"artist_id"`
}

type ArtistLink struct {
	ID       int64  `json:"id"`
	Link     string `json:"link"`
	ArtistID int64  `json:"artist_id"`
}

type ArtistsGroup struct {
	ArtistID int64 `json:"artist_id"`
	GroupID  int64 `json:"group_id"`
}

type Character struct {
	ID        int64  `json:"id"`
	Character string `json:"character"`
	Count     int64  `json:"count"`
}

type Group struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Parody struct {
	ID     int64  `json:"id"`
	Parody string `json:"parody"`
	Count  int64  `json:"count"`
}

type Tag struct {
	ID    int64  `json:"id"`
	Tag   string `json:"tag"`
	Count int64  `json:"count"`
}

type Url struct {
	ID        int64  `json:"id"`
	Url       string `json:"url"`
	ArchiveID int64  `json:"archive_id"`
}

type User struct {
	ID            int64      `json:"id"`
	Name          string     `json:"name"`
	Password      string     `json:"password"`
	Session       *string    `json:"session"`
	SessionExpiry *time.Time `json:"session_expiry"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}
