// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: parody.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const addParodyToArchive = `-- name: AddParodyToArchive :exec
insert into archives_parodies (archive_id, parody_id)
values ($1, $2)
`

type AddParodyToArchiveParams struct {
	ArchiveID int64 `json:"archive_id"`
	ParodyID  int64 `json:"parody_id"`
}

func (q *Queries) AddParodyToArchive(ctx context.Context, arg AddParodyToArchiveParams) error {
	_, err := q.db.Exec(ctx, addParodyToArchive, arg.ArchiveID, arg.ParodyID)
	return err
}

const createParody = `-- name: CreateParody :one
insert into parodies (name, count)
values ($1, $2)
returning id, name, count
`

type CreateParodyParams struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) CreateParody(ctx context.Context, arg CreateParodyParams) (Parody, error) {
	row := q.db.QueryRow(ctx, createParody, arg.Name, arg.Count)
	var i Parody
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const getAllParodies = `-- name: GetAllParodies :many
select id, name, count
from parodies
order by id
`

func (q *Queries) GetAllParodies(ctx context.Context) ([]Parody, error) {
	rows, err := q.db.Query(ctx, getAllParodies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parody
	for rows.Next() {
		var i Parody
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByParody = `-- name: GetArchiveIDsByParody :many
select archives.archive_id
from archives
join archives_parodies on archives.id = archives_parodies.archive_id
join parodies on archives_parodies.parody_id = parodies.id
where parodies.name = $1
`

func (q *Queries) GetArchiveIDsByParody(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByParody, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var archive_id string
		if err := rows.Scan(&archive_id); err != nil {
			return nil, err
		}
		items = append(items, archive_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveParodies = `-- name: GetArchiveParodies :many
select parodies.id, parodies.name, parodies.count
from archives
join archives_parodies on archives.id = archives_parodies.archive_id
join parodies on archives_parodies.parody_id = parodies.id
where archives.archive_id = $1
`

func (q *Queries) GetArchiveParodies(ctx context.Context, archiveID string) ([]Parody, error) {
	rows, err := q.db.Query(ctx, getArchiveParodies, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parody
	for rows.Next() {
		var i Parody
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByParody = `-- name: GetArchivesByParody :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date
from archives
join archives_parodies on archives.id = archives_parodies.archive_id
join parodies on archives_parodies.parody_id = parodies.id
where parodies.name = $1
`

type GetArchivesByParodyRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchivesByParody(ctx context.Context, name string) ([]GetArchivesByParodyRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByParody, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByParodyRow
	for rows.Next() {
		var i GetArchivesByParodyRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByParodyList = `-- name: GetArchivesByParodyList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date
from archives
join archives_parodies on archives.id = archives_parodies.archive_id
join parodies on archives_parodies.parody_id = parodies.id
where parodies.name = $1
limit $2
offset $3
`

type GetArchivesByParodyListParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetArchivesByParodyListRow struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    *string    `json:"file_path"`
	ArchiveID   string     `json:"archive_id"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchivesByParodyList(ctx context.Context, arg GetArchivesByParodyListParams) ([]GetArchivesByParodyListRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByParodyList, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByParodyListRow
	for rows.Next() {
		var i GetArchivesByParodyListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.ArchiveID,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParody = `-- name: GetParody :one
select id, name, count
from parodies
where name = $1
`

func (q *Queries) GetParody(ctx context.Context, name string) (Parody, error) {
	row := q.db.QueryRow(ctx, getParody, name)
	var i Parody
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const parodyExists = `-- name: ParodyExists :execresult
select id, name
from parodies
where name = $1
`

func (q *Queries) ParodyExists(ctx context.Context, name string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, parodyExists, name)
}

const removeParodyFromArchive = `-- name: RemoveParodyFromArchive :many
delete from archives_parodies
where archive_id = $1
returning
    parody_id,
    (
        select parodies.count
        from parodies
        where parodies.id = archives_parodies.parody_id
    )
`

type RemoveParodyFromArchiveRow struct {
	ParodyID int64 `json:"parody_id"`
	Count    int64 `json:"count"`
}

func (q *Queries) RemoveParodyFromArchive(ctx context.Context, archiveID int64) ([]RemoveParodyFromArchiveRow, error) {
	rows, err := q.db.Query(ctx, removeParodyFromArchive, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoveParodyFromArchiveRow
	for rows.Next() {
		var i RemoveParodyFromArchiveRow
		if err := rows.Scan(&i.ParodyID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalArchivesWithParody = `-- name: TotalArchivesWithParody :one
select count(archives.archive_id)
from archives
join archives_parodies on archives.id = archives_parodies.archive_id
join parodies on archives_parodies.parody_id = parodies.id
where parodies.name = $1
`

func (q *Queries) TotalArchivesWithParody(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchivesWithParody, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateParodyCount = `-- name: UpdateParodyCount :exec
update parodies
set count = $1
where id = $2
`

type UpdateParodyCountParams struct {
	Count int64 `json:"count"`
	ID    int64 `json:"id"`
}

func (q *Queries) UpdateParodyCount(ctx context.Context, arg UpdateParodyCountParams) error {
	_, err := q.db.Exec(ctx, updateParodyCount, arg.Count, arg.ID)
	return err
}
