// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tag.sql

package repository

import (
	"context"
)

const addTagToArchive = `-- name: AddTagToArchive :exec
insert into archives_tags (archive_id, tag_id)
values ($1, $2)
`

type AddTagToArchiveParams struct {
	ArchiveID int64 `json:"archive_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AddTagToArchive(ctx context.Context, arg AddTagToArchiveParams) error {
	_, err := q.db.Exec(ctx, addTagToArchive, arg.ArchiveID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
insert into tags (tag)
values ( $1 )
returning id, tag
`

func (q *Queries) CreateTag(ctx context.Context, tag string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, tag)
	var i Tag
	err := row.Scan(&i.ID, &i.Tag)
	return i, err
}

const getAllTags = `-- name: GetAllTags :many
select id, tag
from tags
order by id
`

func (q *Queries) GetAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
