// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: url.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const archiveUrlExists = `-- name: ArchiveUrlExists :execresult
select url
from urls
where url = $1
`

func (q *Queries) ArchiveUrlExists(ctx context.Context, url string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, archiveUrlExists, url)
}

const createArchiveURL = `-- name: CreateArchiveURL :exec
insert into urls (url, archive_id)
values ($1, $2)
`

type CreateArchiveURLParams struct {
	Url       string `json:"url"`
	ArchiveID int64  `json:"archive_id"`
}

func (q *Queries) CreateArchiveURL(ctx context.Context, arg CreateArchiveURLParams) error {
	_, err := q.db.Exec(ctx, createArchiveURL, arg.Url, arg.ArchiveID)
	return err
}

const getArchiveURLs = `-- name: GetArchiveURLs :many
select urls.id, urls.url
from archives
join urls on archives.id = urls.archive_id
where archives.archive_id = $1
`

type GetArchiveURLsRow struct {
	ID  int64  `json:"id"`
	Url string `json:"url"`
}

func (q *Queries) GetArchiveURLs(ctx context.Context, archiveID string) ([]GetArchiveURLsRow, error) {
	rows, err := q.db.Query(ctx, getArchiveURLs, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveURLsRow
	for rows.Next() {
		var i GetArchiveURLsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArchiveUrl = `-- name: RemoveArchiveUrl :exec
delete from urls
where archive_id = $1
`

func (q *Queries) RemoveArchiveUrl(ctx context.Context, archiveID int64) error {
	_, err := q.db.Exec(ctx, removeArchiveUrl, archiveID)
	return err
}
