// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package repository

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
insert into users (
  name,
  password,
  created_at,
  updated_at
) values ( $1, $2, $3, $4 )
returning id, name, password, session, session_expiry, created_at, updated_at
`

type CreateUserParams struct {
	Name      string    `json:"name"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.Session,
		&i.SessionExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, name, password, session, session_expiry, created_at, updated_at
from users
where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.Session,
		&i.SessionExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
select id, name, password, session, session_expiry, created_at, updated_at
from users
where name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.Session,
		&i.SessionExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
select id, name, password, session, session_expiry, created_at, updated_at
from users
where session = $1
`

func (q *Queries) GetUserByToken(ctx context.Context, session *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByToken, session)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.Session,
		&i.SessionExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
update users
set session = $1,
    session_expiry = $2
where id = $3
`

type UpdateSessionParams struct {
	Session       *string    `json:"session"`
	SessionExpiry *time.Time `json:"session_expiry"`
	ID            int64      `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession, arg.Session, arg.SessionExpiry, arg.ID)
	return err
}
