-- +goose Up
CREATE TABLE IF NOT EXISTS character (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    count INTEGER NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS character;
