// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archive.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const archiveExists = `-- name: ArchiveExists :execresult
select title
from archive
where title = $1
`

func (q *Queries) ArchiveExists(ctx context.Context, title string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, archiveExists, title)
}

const archiveIDExists = `-- name: ArchiveIDExists :execresult
select id
from archive
where id = $1
`

func (q *Queries) ArchiveIDExists(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, archiveIDExists, id)
}

const countArchives = `-- name: CountArchives :one
select count(*)
from archive
`

func (q *Queries) CountArchives(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArchives)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchArchive = `-- name: CountSearchArchive :many
select count(*)
from archive, websearch_to_tsquery('english', $1) query
where search_vector @@ query
`

func (q *Queries) CountSearchArchive(ctx context.Context, websearchToTsquery string) ([]int64, error) {
	rows, err := q.db.Query(ctx, countSearchArchive, websearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var count int64
		if err := rows.Scan(&count); err != nil {
			return nil, err
		}
		items = append(items, count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createArchive = `-- name: CreateArchive :one
insert into archive (
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    thumb_path,
    created_at,
    updated_at,
    release_date
    )
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
returning
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    thumb_path,
    created_at,
    updated_at,
    release_date
`

type CreateArchiveParams struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

type CreateArchiveRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) CreateArchive(ctx context.Context, arg CreateArchiveParams) (CreateArchiveRow, error) {
	row := q.db.QueryRow(ctx, createArchive,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Language,
		arg.Category,
		arg.PageCount,
		arg.FilePath,
		arg.FileHash,
		arg.ThumbPath,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ReleaseDate,
	)
	var i CreateArchiveRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.ThumbPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const deleteAllArchive = `-- name: DeleteAllArchive :exec
delete from archive
`

func (q *Queries) DeleteAllArchive(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllArchive)
	return err
}

const deleteArchive = `-- name: DeleteArchive :exec
delete from archive
where id = $1
`

func (q *Queries) DeleteArchive(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArchive, id)
	return err
}

const deleteArchiveByFilePath = `-- name: DeleteArchiveByFilePath :exec
delete from archive
where file_path = $1
`

func (q *Queries) DeleteArchiveByFilePath(ctx context.Context, filePath string) error {
	_, err := q.db.Exec(ctx, deleteArchiveByFilePath, filePath)
	return err
}

const filePathExists = `-- name: FilePathExists :execresult
select file_path
from archive
where file_path = $1
`

func (q *Queries) FilePathExists(ctx context.Context, filePath string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, filePathExists, filePath)
}

const getAllArchives = `-- name: GetAllArchives :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.status
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $1
order by archive.id
`

type GetAllArchivesRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Status      *string    `json:"status"`
}

func (q *Queries) GetAllArchives(ctx context.Context, uid uuid.UUID) ([]GetAllArchivesRow, error) {
	rows, err := q.db.Query(ctx, getAllArchives, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllArchivesRow
	for rows.Next() {
		var i GetAllArchivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFilePaths = `-- name: GetAllFilePaths :many
select id, file_path
from archive
`

type GetAllFilePathsRow struct {
	ID       string `json:"id"`
	FilePath string `json:"file_path"`
}

func (q *Queries) GetAllFilePaths(ctx context.Context) ([]GetAllFilePathsRow, error) {
	rows, err := q.db.Query(ctx, getAllFilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFilePathsRow
	for rows.Next() {
		var i GetAllFilePathsRow
		if err := rows.Scan(&i.ID, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByFileHash = `-- name: GetArchiveByFileHash :one
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    thumb_path,
    created_at,
    updated_at,
    release_date
from archive
where file_hash = $1
`

type GetArchiveByFileHashRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchiveByFileHash(ctx context.Context, fileHash string) (GetArchiveByFileHashRow, error) {
	row := q.db.QueryRow(ctx, getArchiveByFileHash, fileHash)
	var i GetArchiveByFileHashRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.ThumbPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const getArchiveByFilePath = `-- name: GetArchiveByFilePath :one
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    thumb_path,
    created_at,
    updated_at,
    release_date
from archive
where file_path = $1
`

type GetArchiveByFilePathRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchiveByFilePath(ctx context.Context, filePath string) (GetArchiveByFilePathRow, error) {
	row := q.db.QueryRow(ctx, getArchiveByFilePath, filePath)
	var i GetArchiveByFilePathRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.ThumbPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const getArchiveByID = `-- name: GetArchiveByID :one
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    thumb_path,
    created_at,
    updated_at,
    release_date
from archive
where id = $1
`

type GetArchiveByIDRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchiveByID(ctx context.Context, id string) (GetArchiveByIDRow, error) {
	row := q.db.QueryRow(ctx, getArchiveByID, id)
	var i GetArchiveByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.ThumbPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const getArchiveList = `-- name: GetArchiveList :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.status
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $3
limit $1
offset $2
`

type GetArchiveListParams struct {
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
	Uid    uuid.UUID `json:"uid"`
}

type GetArchiveListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Status      *string    `json:"status"`
}

func (q *Queries) GetArchiveList(ctx context.Context, arg GetArchiveListParams) ([]GetArchiveListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveList, arg.Limit, arg.Offset, arg.Uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveListRow
	for rows.Next() {
		var i GetArchiveListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveShuffle = `-- name: GetArchiveShuffle :one
select id
from archive
limit $1
offset $2
`

type GetArchiveShuffleParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetArchiveShuffle(ctx context.Context, arg GetArchiveShuffleParams) (string, error) {
	row := q.db.QueryRow(ctx, getArchiveShuffle, arg.Limit, arg.Offset)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getFilePathByID = `-- name: GetFilePathByID :one
select file_path
from archive
where id = $1
`

func (q *Queries) GetFilePathByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getFilePathByID, id)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const getRecentlyReadArchives = `-- name: GetRecentlyReadArchives :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.status
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $1
where reading_progress.last_read is not null
order by reading_progress.last_read
`

type GetRecentlyReadArchivesRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Status      *string    `json:"status"`
}

func (q *Queries) GetRecentlyReadArchives(ctx context.Context, uid uuid.UUID) ([]GetRecentlyReadArchivesRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyReadArchives, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyReadArchivesRow
	for rows.Next() {
		var i GetRecentlyReadArchivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThumbPathByID = `-- name: GetThumbPathByID :one
select thumb_path
from archive
where id = $1
`

func (q *Queries) GetThumbPathByID(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRow(ctx, getThumbPathByID, id)
	var thumb_path *string
	err := row.Scan(&thumb_path)
	return thumb_path, err
}

const searchArchive = `-- name: SearchArchive :many
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    thumb_path,
    created_at,
    updated_at,
    release_date,
    ts_rank_cd(search_vector, query) as rank
from archive, websearch_to_tsquery('english', $1) query
where search_vector @@ query
order by rank desc
`

type SearchArchiveRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Rank        float32    `json:"rank"`
}

func (q *Queries) SearchArchive(ctx context.Context, websearchToTsquery string) ([]SearchArchiveRow, error) {
	rows, err := q.db.Query(ctx, searchArchive, websearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArchiveRow
	for rows.Next() {
		var i SearchArchiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArchiveList = `-- name: SearchArchiveList :many
select
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    thumb_path,
    created_at,
    updated_at,
    release_date,
    ts_rank_cd(search_vector, query) as rank
from archive, websearch_to_tsquery('english', $1) query
where search_vector @@ query
order by rank desc
limit $2
offset $3
`

type SearchArchiveListParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Limit              int32  `json:"limit"`
	Offset             int32  `json:"offset"`
}

type SearchArchiveListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Rank        float32    `json:"rank"`
}

func (q *Queries) SearchArchiveList(ctx context.Context, arg SearchArchiveListParams) ([]SearchArchiveListRow, error) {
	rows, err := q.db.Query(ctx, searchArchiveList, arg.WebsearchToTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArchiveListRow
	for rows.Next() {
		var i SearchArchiveListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const thumbsPathExistsForFilePath = `-- name: ThumbsPathExistsForFilePath :execresult
select thumb_path
from archive
where file_path = $1
`

func (q *Queries) ThumbsPathExistsForFilePath(ctx context.Context, filePath string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, thumbsPathExistsForFilePath, filePath)
}

const updateArchive = `-- name: UpdateArchive :one
update archive
set title = coalesce($3, title),
    summary = coalesce($4, summary),
    language = coalesce($5, language),
    category = coalesce($6, category),
    updated_at = coalesce($1, updated_at),
    release_date = coalesce($7, release_date)
where id = $2
returning
    id,
    title,
    summary,
    language,
    category,
    page_count,
    file_path,
    file_hash,
    thumb_path,
    created_at,
    updated_at,
    release_date
`

type UpdateArchiveParams struct {
	UpdatedAt   time.Time  `json:"updated_at"`
	ID          string     `json:"id"`
	Title       *string    `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	ReleaseDate *time.Time `json:"release_date"`
}

type UpdateArchiveRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) UpdateArchive(ctx context.Context, arg UpdateArchiveParams) (UpdateArchiveRow, error) {
	row := q.db.QueryRow(ctx, updateArchive,
		arg.UpdatedAt,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Language,
		arg.Category,
		arg.ReleaseDate,
	)
	var i UpdateArchiveRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Language,
		&i.Category,
		&i.PageCount,
		&i.FilePath,
		&i.FileHash,
		&i.ThumbPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleaseDate,
	)
	return i, err
}

const updateFileHash = `-- name: UpdateFileHash :exec
update archive
set file_hash = $1,
    updated_at = $2
where id = $3
`

type UpdateFileHashParams struct {
	FileHash  string    `json:"file_hash"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateFileHash(ctx context.Context, arg UpdateFileHashParams) error {
	_, err := q.db.Exec(ctx, updateFileHash, arg.FileHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateFilePath = `-- name: UpdateFilePath :exec
update archive
set file_path = $1,
    updated_at = $2
where id = $3
`

type UpdateFilePathParams struct {
	FilePath  string    `json:"file_path"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateFilePath(ctx context.Context, arg UpdateFilePathParams) error {
	_, err := q.db.Exec(ctx, updateFilePath, arg.FilePath, arg.UpdatedAt, arg.ID)
	return err
}

const updateThumbPath = `-- name: UpdateThumbPath :exec
update archive
set thumb_path = $1,
    updated_at = $2
where id = $3
`

type UpdateThumbPathParams struct {
	ThumbPath *string   `json:"thumb_path"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateThumbPath(ctx context.Context, arg UpdateThumbPathParams) error {
	_, err := q.db.Exec(ctx, updateThumbPath, arg.ThumbPath, arg.UpdatedAt, arg.ID)
	return err
}
