// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const addArtistToArchive = `-- name: AddArtistToArchive :exec
insert into archive_artist (archive_id, artist_id)
values ($1, $2)
`

type AddArtistToArchiveParams struct {
	ArchiveID string `json:"archive_id"`
	ArtistID  int32  `json:"artist_id"`
}

func (q *Queries) AddArtistToArchive(ctx context.Context, arg AddArtistToArchiveParams) error {
	_, err := q.db.Exec(ctx, addArtistToArchive, arg.ArchiveID, arg.ArtistID)
	return err
}

const artistAliasExists = `-- name: ArtistAliasExists :execresult
select alias
from artist_alias
where alias = $1
`

func (q *Queries) ArtistAliasExists(ctx context.Context, alias string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, artistAliasExists, alias)
}

const artistExists = `-- name: ArtistExists :execresult
select name
from artist
where name = $1
`

func (q *Queries) ArtistExists(ctx context.Context, name string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, artistExists, name)
}

const artistUrlExists = `-- name: ArtistUrlExists :execresult
select url
from artist_url
where url = $1
`

func (q *Queries) ArtistUrlExists(ctx context.Context, url string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, artistUrlExists, url)
}

const createAlias = `-- name: CreateAlias :exec
insert into artist_alias (alias, artist_id)
values ($1, $2)
`

type CreateAliasParams struct {
	Alias    string `json:"alias"`
	ArtistID int32  `json:"artist_id"`
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) error {
	_, err := q.db.Exec(ctx, createAlias, arg.Alias, arg.ArtistID)
	return err
}

const createArtist = `-- name: CreateArtist :one
insert into artist (name, count)
values ($1, $2)
returning id, name, count
`

type CreateArtistParams struct {
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, arg.Name, arg.Count)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const createArtistUrl = `-- name: CreateArtistUrl :exec
insert into artist_url (url, artist_id)
values ($1, $2)
`

type CreateArtistUrlParams struct {
	Url      string `json:"url"`
	ArtistID int32  `json:"artist_id"`
}

func (q *Queries) CreateArtistUrl(ctx context.Context, arg CreateArtistUrlParams) error {
	_, err := q.db.Exec(ctx, createArtistUrl, arg.Url, arg.ArtistID)
	return err
}

const deleteArtist = `-- name: DeleteArtist :exec
delete from artist
where id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const getAllArtists = `-- name: GetAllArtists :many
select id, name, count
from artist
order by id
`

func (q *Queries) GetAllArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getAllArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveArtists = `-- name: GetArchiveArtists :many
select artist.id, artist.name, artist.count
from archive
join archive_artist on archive.id = archive_artist.archive_id
join artist on archive_artist.artist_id = artist.id
where archive.id = $1
`

func (q *Queries) GetArchiveArtists(ctx context.Context, id string) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArchiveArtists, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByArtist = `-- name: GetArchiveByArtist :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date
from archive
join archive_artist on archive.id = archive_artist.archive_id
join artist on archive_artist.artist_id = artist.id
where artist.name = $1
`

type GetArchiveByArtistRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchiveByArtist(ctx context.Context, name string) ([]GetArchiveByArtistRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByArtist, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByArtistRow
	for rows.Next() {
		var i GetArchiveByArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByArtistList = `-- name: GetArchiveByArtistList :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date
from archive
join archive_artist on archive.id = archive_artist.archive_id
join artist on archive_artist.artist_id = artist.id
where artist.name = $1
limit $2
offset $3
`

type GetArchiveByArtistListParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetArchiveByArtistListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetArchiveByArtistList(ctx context.Context, arg GetArchiveByArtistListParams) ([]GetArchiveByArtistListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByArtistList, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByArtistListRow
	for rows.Next() {
		var i GetArchiveByArtistListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByArtist = `-- name: GetArchiveIDsByArtist :many
select archive.id
from archive
join archive_artist on archive.id = archive_artist.archive_id
join artist on archive_artist.artist_id = artist.id
where artist.name = $1
`

func (q *Queries) GetArchiveIDsByArtist(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByArtist, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistAliases = `-- name: GetArtistAliases :many
select artist_alias.id, artist_alias.alias
from artist
join artist_alias on artist.id = artist_alias.artist_id
where name = $1
`

type GetArtistAliasesRow struct {
	ID    int32  `json:"id"`
	Alias string `json:"alias"`
}

func (q *Queries) GetArtistAliases(ctx context.Context, name string) ([]GetArtistAliasesRow, error) {
	rows, err := q.db.Query(ctx, getArtistAliases, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistAliasesRow
	for rows.Next() {
		var i GetArtistAliasesRow
		if err := rows.Scan(&i.ID, &i.Alias); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistByName = `-- name: GetArtistByName :one
select id, name, count
from artist
where name = $1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const getArtistList = `-- name: GetArtistList :many
select id, name, count
from artist
order by $1
limit $2
offset $3
`

type GetArtistListParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetArtistList(ctx context.Context, arg GetArtistListParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtistList, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistUrls = `-- name: GetArtistUrls :many
select artist_url.id, artist_url.url
from artist
join artist_url on artist.id = artist_url.artist_id
where name = $1
`

type GetArtistUrlsRow struct {
	ID  int32  `json:"id"`
	Url string `json:"url"`
}

func (q *Queries) GetArtistUrls(ctx context.Context, name string) ([]GetArtistUrlsRow, error) {
	rows, err := q.db.Query(ctx, getArtistUrls, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistUrlsRow
	for rows.Next() {
		var i GetArtistUrlsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArtistAliases = `-- name: RemoveArtistAliases :exec
delete from artist_alias
where artist_id = $1
`

func (q *Queries) RemoveArtistAliases(ctx context.Context, artistID int32) error {
	_, err := q.db.Exec(ctx, removeArtistAliases, artistID)
	return err
}

const removeArtistFromArchive = `-- name: RemoveArtistFromArchive :many
delete from archive_artist
where archive_id = $1
returning
    artist_id,
    (select artist.count from artist where artist.id = archive_artist.artist_id)
`

type RemoveArtistFromArchiveRow struct {
	ArtistID int32 `json:"artist_id"`
	Count    int32 `json:"count"`
}

func (q *Queries) RemoveArtistFromArchive(ctx context.Context, archiveID string) ([]RemoveArtistFromArchiveRow, error) {
	rows, err := q.db.Query(ctx, removeArtistFromArchive, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoveArtistFromArchiveRow
	for rows.Next() {
		var i RemoveArtistFromArchiveRow
		if err := rows.Scan(&i.ArtistID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArtistUrls = `-- name: RemoveArtistUrls :exec
delete from artist_url
where artist_id = $1
`

func (q *Queries) RemoveArtistUrls(ctx context.Context, artistID int32) error {
	_, err := q.db.Exec(ctx, removeArtistUrls, artistID)
	return err
}

const totalArtists = `-- name: TotalArtists :one
select count(id)
from artist
`

func (q *Queries) TotalArtists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalArtists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateArtist = `-- name: UpdateArtist :one
update artist
set name = $1
where name = $2::text
returning id, name, count
`

type UpdateArtistParams struct {
	Name    string `json:"name"`
	OldName string `json:"old_name"`
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, updateArtist, arg.Name, arg.OldName)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const updateArtistCount = `-- name: UpdateArtistCount :exec
update artist
set count = $1
where id = $2
`

type UpdateArtistCountParams struct {
	Count int32 `json:"count"`
	ID    int32 `json:"id"`
}

func (q *Queries) UpdateArtistCount(ctx context.Context, arg UpdateArtistCountParams) error {
	_, err := q.db.Exec(ctx, updateArtistCount, arg.Count, arg.ID)
	return err
}
