// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const categoryExists = `-- name: CategoryExists :execresult
select category
from archive
where category = $1
`

func (q *Queries) CategoryExists(ctx context.Context, category *string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, categoryExists, category)
}

const getAllCategory = `-- name: GetAllCategory :many
select category
from archive
where category is not null
`

func (q *Queries) GetAllCategory(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getAllCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var category *string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByCategory = `-- name: GetArchiveByCategory :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $2
where category = $1
`

type GetArchiveByCategoryParams struct {
	Category *string   `json:"category"`
	Uid      uuid.UUID `json:"uid"`
}

type GetArchiveByCategoryRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchiveByCategory(ctx context.Context, arg GetArchiveByCategoryParams) ([]GetArchiveByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByCategory, arg.Category, arg.Uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByCategoryRow
	for rows.Next() {
		var i GetArchiveByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByCategoryList = `-- name: GetArchiveByCategoryList :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $4
where category = $1
limit $2
offset $3
`

type GetArchiveByCategoryListParams struct {
	Category *string   `json:"category"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Uid      uuid.UUID `json:"uid"`
}

type GetArchiveByCategoryListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchiveByCategoryList(ctx context.Context, arg GetArchiveByCategoryListParams) ([]GetArchiveByCategoryListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByCategoryList,
		arg.Category,
		arg.Limit,
		arg.Offset,
		arg.Uid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByCategoryListRow
	for rows.Next() {
		var i GetArchiveByCategoryListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByCategory = `-- name: GetArchiveIDsByCategory :many
select archive.id
from archive
where category = $1
`

func (q *Queries) GetArchiveIDsByCategory(ctx context.Context, category *string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalArchiveWithCategory = `-- name: TotalArchiveWithCategory :one
select count(id)
from archive
where category = $1
`

func (q *Queries) TotalArchiveWithCategory(ctx context.Context, category *string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchiveWithCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}
