// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const addCharacterToArchive = `-- name: AddCharacterToArchive :exec
insert into archive_character (archive_id, character_id)
values ($1, $2)
`

type AddCharacterToArchiveParams struct {
	ArchiveID   string `json:"archive_id"`
	CharacterID int32  `json:"character_id"`
}

func (q *Queries) AddCharacterToArchive(ctx context.Context, arg AddCharacterToArchiveParams) error {
	_, err := q.db.Exec(ctx, addCharacterToArchive, arg.ArchiveID, arg.CharacterID)
	return err
}

const bulkAddArchiveCharacters = `-- name: BulkAddArchiveCharacters :exec
insert into archive_character (archive_id, character_id)
select $1, unnest($2::int[])
`

type BulkAddArchiveCharactersParams struct {
	ArchiveID  string  `json:"archive_id"`
	Characters []int32 `json:"characters"`
}

func (q *Queries) BulkAddArchiveCharacters(ctx context.Context, arg BulkAddArchiveCharactersParams) error {
	_, err := q.db.Exec(ctx, bulkAddArchiveCharacters, arg.ArchiveID, arg.Characters)
	return err
}

const characterExists = `-- name: CharacterExists :execresult
select id, name
from character
where name = $1
`

func (q *Queries) CharacterExists(ctx context.Context, name string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, characterExists, name)
}

const createCharacter = `-- name: CreateCharacter :one
insert into character (name, count)
values ($1, $2)
returning id, name, count
`

type CreateCharacterParams struct {
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter, arg.Name, arg.Count)
	var i Character
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const decrementCharacterCount = `-- name: DecrementCharacterCount :exec
update character
set count = count - 1
where id = any($1::int[])
`

func (q *Queries) DecrementCharacterCount(ctx context.Context, characters []int32) error {
	_, err := q.db.Exec(ctx, decrementCharacterCount, characters)
	return err
}

const deleteAllCharacter = `-- name: DeleteAllCharacter :exec
delete from character
`

func (q *Queries) DeleteAllCharacter(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCharacter)
	return err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
delete from character
where id = $1
`

func (q *Queries) DeleteCharacter(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCharacter, id)
	return err
}

const ensureCharacterExist = `-- name: EnsureCharacterExist :many
insert into character (name, count)
select unnest($1::text[]), 0
on conflict (name) do update
set name = excluded.name
returning id, name
`

type EnsureCharacterExistRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) EnsureCharacterExist(ctx context.Context, characters []string) ([]EnsureCharacterExistRow, error) {
	rows, err := q.db.Query(ctx, ensureCharacterExist, characters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnsureCharacterExistRow
	for rows.Next() {
		var i EnsureCharacterExistRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCharacter = `-- name: GetAllCharacter :many
select id, name, count
from character
order by id
`

func (q *Queries) GetAllCharacter(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, getAllCharacter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByCharacter = `-- name: GetArchiveByCharacter :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page
from archive
join archive_character on archive.id = archive_character.archive_id
join character on archive_character.character_id = character.id
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $2
where character.name = $1
`

type GetArchiveByCharacterParams struct {
	Name string    `json:"name"`
	Uid  uuid.UUID `json:"uid"`
}

type GetArchiveByCharacterRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchiveByCharacter(ctx context.Context, arg GetArchiveByCharacterParams) ([]GetArchiveByCharacterRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByCharacter, arg.Name, arg.Uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByCharacterRow
	for rows.Next() {
		var i GetArchiveByCharacterRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByCharacterList = `-- name: GetArchiveByCharacterList :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page
from archive
join archive_character on archive.id = archive_character.archive_id
join character on archive_character.character_id = character.id
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $4
where character.name = $1
order by
    case when $5::text = 'title_asc' then archive.title end asc,
    case when $5 = 'title_desc' then archive.title end desc nulls last,
    case when $5 = 'page_count_asc' then archive.page_count end asc,
    case when $5 = 'page_count_desc' then archive.page_count end desc nulls last,
    case when $5 = 'created_at_asc' then archive.created_at end asc,
    case when $5 = 'created_at_desc' then archive.created_at end desc nulls last,
    case when $5 = 'updated_at_asc' then archive.updated_at end asc,
    case when $5 = 'updated_at_desc' then archive.updated_at end desc nulls last,
    case when $5 = 'release_date_asc' then archive.release_date end asc,
    case
        when $5 = 'release_date_desc' then archive.release_date
    end desc nulls last,
    case when $5 = 'last_read_asc' then reading_progress.last_read end asc,
    case
        when $5 = 'last_read_desc' then reading_progress.last_read
    end desc nulls last
limit $2
offset $3
`

type GetArchiveByCharacterListParams struct {
	Name    string    `json:"name"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
	Uid     uuid.UUID `json:"uid"`
	OrderBy string    `json:"order_by"`
}

type GetArchiveByCharacterListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchiveByCharacterList(ctx context.Context, arg GetArchiveByCharacterListParams) ([]GetArchiveByCharacterListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByCharacterList,
		arg.Name,
		arg.Limit,
		arg.Offset,
		arg.Uid,
		arg.OrderBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByCharacterListRow
	for rows.Next() {
		var i GetArchiveByCharacterListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveCharacterIDs = `-- name: GetArchiveCharacterIDs :many
select character.id
from archive
join archive_character on archive.id = archive_character.archive_id
join character on archive_character.character_id = character.id
where archive.id = $1
`

func (q *Queries) GetArchiveCharacterIDs(ctx context.Context, id string) ([]int32, error) {
	rows, err := q.db.Query(ctx, getArchiveCharacterIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveCharacters = `-- name: GetArchiveCharacters :many
select character.id, character.name, character.count
from archive
join archive_character on archive.id = archive_character.archive_id
join character on archive_character.character_id = character.id
where archive.id = $1
`

func (q *Queries) GetArchiveCharacters(ctx context.Context, id string) ([]Character, error) {
	rows, err := q.db.Query(ctx, getArchiveCharacters, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByCharacter = `-- name: GetArchiveIDsByCharacter :many
select archive.id
from archive
join archive_character on archive.id = archive_character.archive_id
join character on archive_character.character_id = character.id
where character.name = $1
`

func (q *Queries) GetArchiveIDsByCharacter(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByCharacter, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByCharacters = `-- name: GetArchiveIDsByCharacters :many
select archive.id
from archive
join archive_character on archive.id = archive_character.archive_id
join character on archive_character.character_id = character.id
where character.name = any($1::text[])
group by archive.id
having count(distinct character.id) = $2
`

type GetArchiveIDsByCharactersParams struct {
	Characters []string `json:"characters"`
	Amount     int32    `json:"amount"`
}

func (q *Queries) GetArchiveIDsByCharacters(ctx context.Context, arg GetArchiveIDsByCharactersParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByCharacters, arg.Characters, arg.Amount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacter = `-- name: GetCharacter :one
select id, name, count
from character
where name = $1
`

func (q *Queries) GetCharacter(ctx context.Context, name string) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, name)
	var i Character
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const incrementCharacterCount = `-- name: IncrementCharacterCount :exec
update character
set count = count + 1
where id = any($1::int[])
`

func (q *Queries) IncrementCharacterCount(ctx context.Context, characters []int32) error {
	_, err := q.db.Exec(ctx, incrementCharacterCount, characters)
	return err
}

const removeCharacterFromArchive = `-- name: RemoveCharacterFromArchive :exec
delete from archive_character
where archive_id = $1 and character_id = any($2::int[])
`

type RemoveCharacterFromArchiveParams struct {
	ArchiveID  string  `json:"archive_id"`
	Characters []int32 `json:"characters"`
}

func (q *Queries) RemoveCharacterFromArchive(ctx context.Context, arg RemoveCharacterFromArchiveParams) error {
	_, err := q.db.Exec(ctx, removeCharacterFromArchive, arg.ArchiveID, arg.Characters)
	return err
}

const totalArchiveWithCharacter = `-- name: TotalArchiveWithCharacter :one
select count(archive.id)
from archive
join archive_character on archive.id = archive_character.archive_id
join character on archive_character.character_id = character.id
where character.name = $1
`

func (q *Queries) TotalArchiveWithCharacter(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchiveWithCharacter, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
