// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const addCharacterToArchive = `-- name: AddCharacterToArchive :exec
insert into archives_characters (archive_id, character_id)
values ($1, $2)
`

type AddCharacterToArchiveParams struct {
	ArchiveID   string `json:"archive_id"`
	CharacterID int64  `json:"character_id"`
}

func (q *Queries) AddCharacterToArchive(ctx context.Context, arg AddCharacterToArchiveParams) error {
	_, err := q.db.Exec(ctx, addCharacterToArchive, arg.ArchiveID, arg.CharacterID)
	return err
}

const characterExists = `-- name: CharacterExists :execresult
select id, name
from characters
where name = $1
`

func (q *Queries) CharacterExists(ctx context.Context, name string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, characterExists, name)
}

const createCharacter = `-- name: CreateCharacter :one
insert into characters (name, count)
values ($1, $2)
returning id, name, count
`

type CreateCharacterParams struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter, arg.Name, arg.Count)
	var i Character
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const getAllCharacter = `-- name: GetAllCharacter :many
select id, name, count
from characters
order by id
`

func (q *Queries) GetAllCharacter(ctx context.Context) ([]Character, error) {
	rows, err := q.db.Query(ctx, getAllCharacter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveCharacters = `-- name: GetArchiveCharacters :many
select characters.id, characters.name, characters.count
from archives
join archives_characters on archives.id = archives_characters.archive_id
join characters on archives_characters.character_id = characters.id
where archives.id = $1
`

func (q *Queries) GetArchiveCharacters(ctx context.Context, id string) ([]Character, error) {
	rows, err := q.db.Query(ctx, getArchiveCharacters, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByCharacter = `-- name: GetArchiveIDsByCharacter :many
select archives.id
from archives
join archives_characters on archives.id = archives_characters.archive_id
join characters on archives_characters.character_id = characters.id
where characters.name = $1
`

func (q *Queries) GetArchiveIDsByCharacter(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByCharacter, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByCharacter = `-- name: GetArchivesByCharacter :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    -- archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page
from archives
join archives_characters on archives.id = archives_characters.archive_id
join characters on archives_characters.character_id = characters.id
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $2
where characters.name = $1
`

type GetArchivesByCharacterParams struct {
	Name string    `json:"name"`
	Uid  uuid.UUID `json:"uid"`
}

type GetArchivesByCharacterRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchivesByCharacter(ctx context.Context, arg GetArchivesByCharacterParams) ([]GetArchivesByCharacterRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByCharacter, arg.Name, arg.Uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByCharacterRow
	for rows.Next() {
		var i GetArchivesByCharacterRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByCharacterList = `-- name: GetArchivesByCharacterList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    -- archives.archive_id,
    archives.hash,
    archives.thumbs_path,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page
from archives
join archives_characters on archives.id = archives_characters.archive_id
join characters on archives_characters.character_id = characters.id
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $4
where characters.name = $1
limit $2
offset $3
`

type GetArchivesByCharacterListParams struct {
	Name   string    `json:"name"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
	Uid    uuid.UUID `json:"uid"`
}

type GetArchivesByCharacterListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchivesByCharacterList(ctx context.Context, arg GetArchivesByCharacterListParams) ([]GetArchivesByCharacterListRow, error) {
	rows, err := q.db.Query(ctx, getArchivesByCharacterList,
		arg.Name,
		arg.Limit,
		arg.Offset,
		arg.Uid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByCharacterListRow
	for rows.Next() {
		var i GetArchivesByCharacterListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacter = `-- name: GetCharacter :one
select id, name, count
from characters
where name = $1
`

func (q *Queries) GetCharacter(ctx context.Context, name string) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, name)
	var i Character
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const removeCharacterFromArchive = `-- name: RemoveCharacterFromArchive :many
delete from archives_characters
where archive_id = $1
returning
    character_id,
    (
        select characters.count
        from characters
        where characters.id = archives_characters.character_id
    )
`

type RemoveCharacterFromArchiveRow struct {
	CharacterID int64 `json:"character_id"`
	Count       int64 `json:"count"`
}

func (q *Queries) RemoveCharacterFromArchive(ctx context.Context, archiveID string) ([]RemoveCharacterFromArchiveRow, error) {
	rows, err := q.db.Query(ctx, removeCharacterFromArchive, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoveCharacterFromArchiveRow
	for rows.Next() {
		var i RemoveCharacterFromArchiveRow
		if err := rows.Scan(&i.CharacterID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalArchivesWithCharacter = `-- name: TotalArchivesWithCharacter :one
select count(archives.id)
from archives
join archives_characters on archives.id = archives_characters.archive_id
join characters on archives_characters.character_id = characters.id
where characters.name = $1
`

func (q *Queries) TotalArchivesWithCharacter(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchivesWithCharacter, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateCharacterCount = `-- name: UpdateCharacterCount :exec
update characters
set count = $1
where id = $2
`

type UpdateCharacterCountParams struct {
	Count int64 `json:"count"`
	ID    int64 `json:"id"`
}

func (q *Queries) UpdateCharacterCount(ctx context.Context, arg UpdateCharacterCountParams) error {
	_, err := q.db.Exec(ctx, updateCharacterCount, arg.Count, arg.ID)
	return err
}
