// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download.sql

package repository

/*
import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDownload = `-- name: CreateDownload :one
INSERT INTO downloads (id, url, source, filename, status, progress, error, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, url, source, filename, status, progress, error, created_at, updated_at, speed, total_size, downloaded, started_at, can_resume, resume_supported
`

type CreateDownloadParams struct {
	ID        uuid.UUID `json:"id"`
	Url       string    `json:"url"`
	Source    string    `json:"source"`
	Filename  string    `json:"filename"`
	Status    string    `json:"status"`
	Progress  *int32    `json:"progress"`
	Error     *string   `json:"error"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, createDownload,
		arg.ID,
		arg.Url,
		arg.Source,
		arg.Filename,
		arg.Status,
		arg.Progress,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Source,
		&i.Filename,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Speed,
		&i.TotalSize,
		&i.Downloaded,
		&i.StartedAt,
		&i.CanResume,
		&i.ResumeSupported,
	)
	return i, err
}

const deleteDownload = `-- name: DeleteDownload :exec
delete from downloads
where id = $1
`

func (q *Queries) DeleteDownload(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDownload, id)
	return err
}

const getAllDownloads = `-- name: GetAllDownloads :many
select id, url, source, filename, status, progress, error, created_at, updated_at, speed, total_size, downloaded, started_at, can_resume, resume_supported
from downloads
order by created_at desc
`

func (q *Queries) GetAllDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.Query(ctx, getAllDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Source,
			&i.Filename,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Speed,
			&i.TotalSize,
			&i.Downloaded,
			&i.StartedAt,
			&i.CanResume,
			&i.ResumeSupported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownload = `-- name: GetDownload :one
select id, url, source, filename, status, progress, error, created_at, updated_at, speed, total_size, downloaded, started_at, can_resume, resume_supported
from downloads
where id = $1
`

func (q *Queries) GetDownload(ctx context.Context, id uuid.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, getDownload, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Source,
		&i.Filename,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Speed,
		&i.TotalSize,
		&i.Downloaded,
		&i.StartedAt,
		&i.CanResume,
		&i.ResumeSupported,
	)
	return i, err
}

const getDownloadsByStatus = `-- name: GetDownloadsByStatus :many
select id, url, source, filename, status, progress, error, created_at, updated_at, speed, total_size, downloaded, started_at, can_resume, resume_supported
from downloads
where status = any($1::text[])
order by created_at desc
`

func (q *Queries) GetDownloadsByStatus(ctx context.Context, dollar_1 []string) ([]Download, error) {
	rows, err := q.db.Query(ctx, getDownloadsByStatus, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Source,
			&i.Filename,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Speed,
			&i.TotalSize,
			&i.Downloaded,
			&i.StartedAt,
			&i.CanResume,
			&i.ResumeSupported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingDownloads = `-- name: GetPendingDownloads :many
select id, url, source, filename, status, progress, error, created_at, updated_at, speed, total_size, downloaded, started_at, can_resume, resume_supported
from downloads
where status in ('pending', 'downloading')
order by created_at asc
`

func (q *Queries) GetPendingDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.Query(ctx, getPendingDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Source,
			&i.Filename,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Speed,
			&i.TotalSize,
			&i.Downloaded,
			&i.StartedAt,
			&i.CanResume,
			&i.ResumeSupported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadProgress = `-- name: UpdateDownloadProgress :one
UPDATE downloads
SET progress = $2, updated_at = $3
WHERE id = $1
RETURNING id, url, source, filename, status, progress, error, created_at, updated_at, speed, total_size, downloaded, started_at, can_resume, resume_supported
`

type UpdateDownloadProgressParams struct {
	ID        uuid.UUID `json:"id"`
	Progress  *int32    `json:"progress"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) (Download, error) {
	row := q.db.QueryRow(ctx, updateDownloadProgress, arg.ID, arg.Progress, arg.UpdatedAt)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Source,
		&i.Filename,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Speed,
		&i.TotalSize,
		&i.Downloaded,
		&i.StartedAt,
		&i.CanResume,
		&i.ResumeSupported,
	)
	return i, err
}

const updateDownloadStatus = `-- name: UpdateDownloadStatus :one
UPDATE downloads
SET status = $2, progress = $3, error = $4, updated_at = $5
WHERE id = $1
RETURNING id, url, source, filename, status, progress, error, created_at, updated_at, speed, total_size, downloaded, started_at, can_resume, resume_supported
`

type UpdateDownloadStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	Progress  *int32    `json:"progress"`
	Error     *string   `json:"error"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) (Download, error) {
	row := q.db.QueryRow(ctx, updateDownloadStatus,
		arg.ID,
		arg.Status,
		arg.Progress,
		arg.Error,
		arg.UpdatedAt,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Source,
		&i.Filename,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Speed,
		&i.TotalSize,
		&i.Downloaded,
		&i.StartedAt,
		&i.CanResume,
		&i.ResumeSupported,
	)
	return i, err
}
*/
