// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorites.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const addFavoriteArchive = `-- name: AddFavoriteArchive :exec
insert into favorite_archives (archive_id, user_id, favorited_at)
values ($1, $2, $3)
`

type AddFavoriteArchiveParams struct {
	ArchiveID   string    `json:"archive_id"`
	UserID      uuid.UUID `json:"user_id"`
	FavoritedAt time.Time `json:"favorited_at"`
}

func (q *Queries) AddFavoriteArchive(ctx context.Context, arg AddFavoriteArchiveParams) error {
	_, err := q.db.Exec(ctx, addFavoriteArchive, arg.ArchiveID, arg.UserID, arg.FavoritedAt)
	return err
}

const archiveIsFavorited = `-- name: ArchiveIsFavorited :execresult
select archive_id
from favorite_archives
where user_id = $1 and archive_id = $2
`

type ArchiveIsFavoritedParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ArchiveID string    `json:"archive_id"`
}

func (q *Queries) ArchiveIsFavorited(ctx context.Context, arg ArchiveIsFavoritedParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, archiveIsFavorited, arg.UserID, arg.ArchiveID)
}

const countFavoriteFilteredArchives = `-- name: CountFavoriteFilteredArchives :one
select count(archives.id)
from archives
where
    archives.id = any($1::text[])
    and archives.id in (
        select archives.id
        from archives
        join favorite_archives on archives.id = favorite_archives.archive_id
        join users on favorite_archives.user_id = users.id
        where users.id = $2::uuid
    )
`

type CountFavoriteFilteredArchivesParams struct {
	Ids    []string  `json:"ids"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CountFavoriteFilteredArchives(ctx context.Context, arg CountFavoriteFilteredArchivesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoriteFilteredArchives, arg.Ids, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserFavoriteArchives = `-- name: CountUserFavoriteArchives :one
select count(archive_id)
from favorite_archives
where user_id = $1
`

func (q *Queries) CountUserFavoriteArchives(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserFavoriteArchives, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFavoriteArchiveSortList = `-- name: GetFavoriteArchiveSortList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.cover_img,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page
from archives
join favorite_archives on archives.id = favorite_archives.archive_id
join users on favorite_archives.user_id = users.id
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $3::uuid
where users.id = $3::uuid
order by
    case when $4::text = 'title_asc' then archives.title end asc,
    case when $4 = 'title_desc' then archives.title end desc nulls last,
    case when $4 = 'page_count_asc' then archives.page_count end asc,
    case
        when $4 = 'page_count_desc' then archives.page_count
    end desc nulls last,
    case when $4 = 'created_at_asc' then archives.created_at end asc,
    case
        when $4 = 'created_at_desc' then archives.created_at
    end desc nulls last,
    case when $4 = 'updated_at_asc' then archives.updated_at end asc,
    case
        when $4 = 'updated_at_desc' then archives.updated_at
    end desc nulls last,
    case when $4 = 'release_date_asc' then archives.release_date end asc,
    case
        when $4 = 'release_date_desc' then archives.release_date
    end desc nulls last,
    case
        when $4 = 'favorited_at_asc' then favorite_archives.favorited_at
    end asc,
    case
        when $4 = 'favorited_at_desc' then favorite_archives.favorited_at
    end desc nulls last
limit $1
offset $2
`

type GetFavoriteArchiveSortListParams struct {
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
	UserID  uuid.UUID `json:"user_id"`
	OrderBy string    `json:"order_by"`
}

type GetFavoriteArchiveSortListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	CoverImg    *string    `json:"cover_img"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetFavoriteArchiveSortList(ctx context.Context, arg GetFavoriteArchiveSortListParams) ([]GetFavoriteArchiveSortListRow, error) {
	rows, err := q.db.Query(ctx, getFavoriteArchiveSortList,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.OrderBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFavoriteArchiveSortListRow
	for rows.Next() {
		var i GetFavoriteArchiveSortListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.CoverImg,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavoriteArchivesFilter = `-- name: GetFavoriteArchivesFilter :one
select archives.id
from archives
join favorite_archives on archives.id = favorite_archives.archive_id
where
    archives.id = any($3::text[])
    and archives.id in (
        select archives.id
        from archives
        join favorite_archives on archives.id = favorite_archives.archive_id
        join users on favorite_archives.user_id = users.id
        where users.id = $4::uuid
    )
limit $1
offset $2
`

type GetFavoriteArchivesFilterParams struct {
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
	Ids    []string  `json:"ids"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetFavoriteArchivesFilter(ctx context.Context, arg GetFavoriteArchivesFilterParams) (string, error) {
	row := q.db.QueryRow(ctx, getFavoriteArchivesFilter,
		arg.Limit,
		arg.Offset,
		arg.Ids,
		arg.UserID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getFavoriteArchivesFilterSortList = `-- name: GetFavoriteArchivesFilterSortList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.cover_img,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page
from archives
join favorite_archives on archives.id = favorite_archives.archive_id
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $3::uuid
where
    archives.id = any($4::text[])
    and archives.id in (
        select archives.id
        from archives
        join favorite_archives on archives.id = favorite_archives.archive_id
        join users on favorite_archives.user_id = users.id
        where users.id = $3::uuid
    )
order by
    case when $5::text = 'title_asc' then archives.title end asc,
    case when $5 = 'title_desc' then archives.title end desc nulls last,
    case when $5 = 'page_count_asc' then archives.page_count end asc,
    case
        when $5 = 'page_count_desc' then archives.page_count
    end desc nulls last,
    case when $5 = 'created_at_asc' then archives.created_at end asc,
    case
        when $5 = 'created_at_desc' then archives.created_at
    end desc nulls last,
    case when $5 = 'updated_at_asc' then archives.updated_at end asc,
    case
        when $5 = 'updated_at_desc' then archives.updated_at
    end desc nulls last,
    case when $5 = 'release_date_asc' then archives.release_date end asc,
    case
        when $5 = 'release_date_desc' then archives.release_date
    end desc nulls last,
    case
        when $5 = 'favorited_at_asc' then favorite_archives.favorited_at
    end asc,
    case
        when $5 = 'favorited_at_desc' then favorite_archives.favorited_at
    end desc nulls last
limit $1
offset $2
`

type GetFavoriteArchivesFilterSortListParams struct {
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
	UserID  uuid.UUID `json:"user_id"`
	Ids     []string  `json:"ids"`
	OrderBy string    `json:"order_by"`
}

type GetFavoriteArchivesFilterSortListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	CoverImg    *string    `json:"cover_img"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetFavoriteArchivesFilterSortList(ctx context.Context, arg GetFavoriteArchivesFilterSortListParams) ([]GetFavoriteArchivesFilterSortListRow, error) {
	rows, err := q.db.Query(ctx, getFavoriteArchivesFilterSortList,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Ids,
		arg.OrderBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFavoriteArchivesFilterSortListRow
	for rows.Next() {
		var i GetFavoriteArchivesFilterSortListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.CoverImg,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFavoriteArchivesAll = `-- name: GetUserFavoriteArchivesAll :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.cover_img,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date
from archives
join favorite_archives on archives.id = favorite_archives.archive_id
join users on favorite_archives.user_id = users.id
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = users.id
where users.id = $1
order by favorited_at desc
`

type GetUserFavoriteArchivesAllRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	CoverImg    *string    `json:"cover_img"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetUserFavoriteArchivesAll(ctx context.Context, id uuid.UUID) ([]GetUserFavoriteArchivesAllRow, error) {
	rows, err := q.db.Query(ctx, getUserFavoriteArchivesAll, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFavoriteArchivesAllRow
	for rows.Next() {
		var i GetUserFavoriteArchivesAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.CoverImg,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFavoriteArchivesList = `-- name: GetUserFavoriteArchivesList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.cover_img,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date
from archives
join favorite_archives on archives.id = favorite_archives.archive_id
join users on favorite_archives.user_id = users.id
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = users.id
where users.id = $1
limit $2
offset $3
`

type GetUserFavoriteArchivesListParams struct {
	ID     uuid.UUID `json:"id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUserFavoriteArchivesListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	CoverImg    *string    `json:"cover_img"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

func (q *Queries) GetUserFavoriteArchivesList(ctx context.Context, arg GetUserFavoriteArchivesListParams) ([]GetUserFavoriteArchivesListRow, error) {
	rows, err := q.db.Query(ctx, getUserFavoriteArchivesList, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFavoriteArchivesListRow
	for rows.Next() {
		var i GetUserFavoriteArchivesListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.CoverImg,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFavoriteArchivesShuffle = `-- name: GetUserFavoriteArchivesShuffle :one
select archives.id
from archives
join favorite_archives on archives.id = favorite_archives.archive_id
join users on favorite_archives.user_id = users.id
where users.id = $1
limit $2
offset $3
`

type GetUserFavoriteArchivesShuffleParams struct {
	ID     uuid.UUID `json:"id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetUserFavoriteArchivesShuffle(ctx context.Context, arg GetUserFavoriteArchivesShuffleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserFavoriteArchivesShuffle, arg.ID, arg.Limit, arg.Offset)
	var id string
	err := row.Scan(&id)
	return id, err
}

const removeFavoriteArchive = `-- name: RemoveFavoriteArchive :exec
delete from favorite_archives
where archive_id = $1 and user_id = $2
`

type RemoveFavoriteArchiveParams struct {
	ArchiveID string    `json:"archive_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveFavoriteArchive(ctx context.Context, arg RemoveFavoriteArchiveParams) error {
	_, err := q.db.Exec(ctx, removeFavoriteArchive, arg.ArchiveID, arg.UserID)
	return err
}
