// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFilteredArchives = `-- name: CountFilteredArchives :one
select count(archives.id)
from archives
where archives.id = any($1::text[])
`

func (q *Queries) CountFilteredArchives(ctx context.Context, ids []string) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredArchives, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArchiveSort = `-- name: GetArchiveSort :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.cover_img,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.state
from archives
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $1
order by
    case when $2::text = 'title_asc' then title end asc,
    case when $2 = 'title_desc' then title end desc nulls last,
    case when $2 = 'page_count_asc' then page_count end asc,
    case when $2 = 'page_count_desc' then page_count end desc nulls last,
    case when $2 = 'created_at_asc' then created_at end asc,
    case when $2 = 'created_at_desc' then created_at end desc nulls last,
    case when $2 = 'updated_at_asc' then updated_at end asc,
    case when $2 = 'updated_at_desc' then updated_at end desc nulls last,
    case when $2 = 'release_date_asc' then release_date end asc,
    case when $2 = 'release_date_desc' then release_date end desc nulls last,
    case when $2 = 'last_read_asc' then reading_progress.last_read end asc,
    case
        when $2 = 'last_read_desc' then reading_progress.last_read
    end desc nulls last
`

type GetArchiveSortParams struct {
	Uid     uuid.UUID `json:"uid"`
	OrderBy string    `json:"order_by"`
}

type GetArchiveSortRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	CoverImg    *string    `json:"cover_img"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	State       *string    `json:"state"`
}

func (q *Queries) GetArchiveSort(ctx context.Context, arg GetArchiveSortParams) ([]GetArchiveSortRow, error) {
	rows, err := q.db.Query(ctx, getArchiveSort, arg.Uid, arg.OrderBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveSortRow
	for rows.Next() {
		var i GetArchiveSortRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.CoverImg,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveSortList = `-- name: GetArchiveSortList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.cover_img,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.state
from archives
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $3
order by
    case when $4::text = 'title_asc' then title end asc,
    case when $4 = 'title_desc' then title end desc nulls last,
    case when $4 = 'page_count_asc' then page_count end asc,
    case when $4 = 'page_count_desc' then page_count end desc nulls last,
    case when $4 = 'created_at_asc' then created_at end asc,
    case when $4 = 'created_at_desc' then created_at end desc nulls last,
    case when $4 = 'updated_at_asc' then updated_at end asc,
    case when $4 = 'updated_at_desc' then updated_at end desc nulls last,
    case when $4 = 'release_date_asc' then release_date end asc,
    case when $4 = 'release_date_desc' then release_date end desc nulls last,
    case when $4 = 'last_read_asc' then reading_progress.last_read end asc,
    case
        when $4 = 'last_read_desc' then reading_progress.last_read
    end desc nulls last
limit $1
offset $2
`

type GetArchiveSortListParams struct {
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
	Uid     uuid.UUID `json:"uid"`
	OrderBy string    `json:"order_by"`
}

type GetArchiveSortListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	CoverImg    *string    `json:"cover_img"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	State       *string    `json:"state"`
}

func (q *Queries) GetArchiveSortList(ctx context.Context, arg GetArchiveSortListParams) ([]GetArchiveSortListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveSortList,
		arg.Limit,
		arg.Offset,
		arg.Uid,
		arg.OrderBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveSortListRow
	for rows.Next() {
		var i GetArchiveSortListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.CoverImg,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesFilter = `-- name: GetArchivesFilter :one
select archives.id
from archives
where archives.id = any($3::text[])
limit $1
offset $2
`

type GetArchivesFilterParams struct {
	Limit  int32    `json:"limit"`
	Offset int32    `json:"offset"`
	Ids    []string `json:"ids"`
}

func (q *Queries) GetArchivesFilter(ctx context.Context, arg GetArchivesFilterParams) (string, error) {
	row := q.db.QueryRow(ctx, getArchivesFilter, arg.Limit, arg.Offset, arg.Ids)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getArchivesFilterSortList = `-- name: GetArchivesFilterSortList :many
select
    archives.id,
    archives.title,
    archives.summary,
    archives.language,
    archives.category,
    archives.page_count,
    archives.file_path,
    archives.file_name,
    archives.hash,
    archives.thumbs_path,
    archives.cover_path,
    archives.cover_img,
    archives.type,
    archives.created_at,
    archives.updated_at,
    archives.release_date,
    reading_progress.page,
    reading_progress.last_read,
    reading_progress.state
from archives
left join
    reading_progress
    on archives.id = reading_progress.archive_id
    and reading_progress.user_id = $3
where archives.id = any($4::text[])
order by
    case when $5::text = 'title_asc' then archives.title end asc,
    case when $5 = 'title_desc' then archives.title end desc nulls last,
    case when $5 = 'page_count_asc' then archives.page_count end asc,
    case
        when $5 = 'page_count_desc' then archives.page_count
    end desc nulls last,
    case when $5 = 'created_at_asc' then archives.created_at end asc,
    case
        when $5 = 'created_at_desc' then archives.created_at
    end desc nulls last,
    case when $5 = 'updated_at_asc' then archives.updated_at end asc,
    case
        when $5 = 'updated_at_desc' then archives.updated_at
    end desc nulls last,
    case when $5 = 'release_date_asc' then archives.release_date end asc,
    case
        when $5 = 'release_date_desc' then archives.release_date
    end desc nulls last,
    case when $5 = 'last_read_asc' then reading_progress.last_read end asc,
    case
        when $5 = 'last_read_desc' then reading_progress.last_read
    end desc nulls last
limit $1
offset $2
`

type GetArchivesFilterSortListParams struct {
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
	Uid     uuid.UUID `json:"uid"`
	Ids     []string  `json:"ids"`
	OrderBy string    `json:"order_by"`
}

type GetArchivesFilterSortListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileName    string     `json:"file_name"`
	Hash        string     `json:"hash"`
	ThumbsPath  *string    `json:"thumbs_path"`
	CoverPath   *string    `json:"cover_path"`
	CoverImg    *string    `json:"cover_img"`
	Type        string     `json:"type"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	State       *string    `json:"state"`
}

func (q *Queries) GetArchivesFilterSortList(ctx context.Context, arg GetArchivesFilterSortListParams) ([]GetArchivesFilterSortListRow, error) {
	rows, err := q.db.Query(ctx, getArchivesFilterSortList,
		arg.Limit,
		arg.Offset,
		arg.Uid,
		arg.Ids,
		arg.OrderBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesFilterSortListRow
	for rows.Next() {
		var i GetArchivesFilterSortListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileName,
			&i.Hash,
			&i.ThumbsPath,
			&i.CoverPath,
			&i.CoverImg,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
			&i.LastRead,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
