// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: language.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const getAllLanguage = `-- name: GetAllLanguage :many
select distinct language
from archive
where language is not null
`

func (q *Queries) GetAllLanguage(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getAllLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var language *string
		if err := rows.Scan(&language); err != nil {
			return nil, err
		}
		items = append(items, language)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByLanguage = `-- name: GetArchiveByLanguage :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $2
where language = $1
`

type GetArchiveByLanguageParams struct {
	Language *string   `json:"language"`
	Uid      uuid.UUID `json:"uid"`
}

type GetArchiveByLanguageRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchiveByLanguage(ctx context.Context, arg GetArchiveByLanguageParams) ([]GetArchiveByLanguageRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByLanguage, arg.Language, arg.Uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByLanguageRow
	for rows.Next() {
		var i GetArchiveByLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByLanguageList = `-- name: GetArchiveByLanguageList :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page
from archive
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $4
where language = $1
limit $2
offset $3
`

type GetArchiveByLanguageListParams struct {
	Language *string   `json:"language"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Uid      uuid.UUID `json:"uid"`
}

type GetArchiveByLanguageListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchiveByLanguageList(ctx context.Context, arg GetArchiveByLanguageListParams) ([]GetArchiveByLanguageListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByLanguageList,
		arg.Language,
		arg.Limit,
		arg.Offset,
		arg.Uid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByLanguageListRow
	for rows.Next() {
		var i GetArchiveByLanguageListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByLanguage = `-- name: GetArchiveIDsByLanguage :many
select archive.id
from archive
where language = $1
`

func (q *Queries) GetArchiveIDsByLanguage(ctx context.Context, language *string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByLanguages = `-- name: GetArchiveIDsByLanguages :many
select archive.id
from archive
where language = any($1::text[])
group by archive.id
having count(distinct archive.id) = $2::int
`

type GetArchiveIDsByLanguagesParams struct {
	Languages []string `json:"languages"`
	Amount    int32    `json:"amount"`
}

func (q *Queries) GetArchiveIDsByLanguages(ctx context.Context, arg GetArchiveIDsByLanguagesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByLanguages, arg.Languages, arg.Amount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const languageExists = `-- name: LanguageExists :execresult
select language
from archive
where language = $1
`

func (q *Queries) LanguageExists(ctx context.Context, language *string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, languageExists, language)
}

const totalArchiveWithLanguage = `-- name: TotalArchiveWithLanguage :one
select count(id)
from archive
where language = $1
`

func (q *Queries) TotalArchiveWithLanguage(ctx context.Context, language *string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchiveWithLanguage, language)
	var count int64
	err := row.Scan(&count)
	return count, err
}
