// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parody.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const addParodyToArchive = `-- name: AddParodyToArchive :exec
insert into archive_parody (archive_id, parody_id)
values ($1, $2)
`

type AddParodyToArchiveParams struct {
	ArchiveID string `json:"archive_id"`
	ParodyID  int32  `json:"parody_id"`
}

func (q *Queries) AddParodyToArchive(ctx context.Context, arg AddParodyToArchiveParams) error {
	_, err := q.db.Exec(ctx, addParodyToArchive, arg.ArchiveID, arg.ParodyID)
	return err
}

const createParody = `-- name: CreateParody :one
insert into parody (name, count)
values ($1, $2)
returning id, name, count
`

type CreateParodyParams struct {
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

func (q *Queries) CreateParody(ctx context.Context, arg CreateParodyParams) (Parody, error) {
	row := q.db.QueryRow(ctx, createParody, arg.Name, arg.Count)
	var i Parody
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const getAllParody = `-- name: GetAllParody :many
select id, name, count
from parody
order by id
`

func (q *Queries) GetAllParody(ctx context.Context) ([]Parody, error) {
	rows, err := q.db.Query(ctx, getAllParody)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parody
	for rows.Next() {
		var i Parody
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByParodyList = `-- name: GetArchiveByParodyList :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $4
where parody.name = $1
limit $2
offset $3
`

type GetArchiveByParodyListParams struct {
	Name   string    `json:"name"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
	Uid    uuid.UUID `json:"uid"`
}

type GetArchiveByParodyListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetArchiveByParodyList(ctx context.Context, arg GetArchiveByParodyListParams) ([]GetArchiveByParodyListRow, error) {
	rows, err := q.db.Query(ctx, getArchiveByParodyList,
		arg.Name,
		arg.Limit,
		arg.Offset,
		arg.Uid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByParodyListRow
	for rows.Next() {
		var i GetArchiveByParodyListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByParody = `-- name: GetArchiveIDsByParody :many
select archive.id
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
where parody.name = $1
`

func (q *Queries) GetArchiveIDsByParody(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getArchiveIDsByParody, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveParody = `-- name: GetArchiveParody :many
select parody.id, parody.name, parody.count
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
where archive.id = $1
`

func (q *Queries) GetArchiveParody(ctx context.Context, id string) ([]Parody, error) {
	rows, err := q.db.Query(ctx, getArchiveParody, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parody
	for rows.Next() {
		var i Parody
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParody = `-- name: GetParody :one
select id, name, count
from parody
where name = $1
`

func (q *Queries) GetParody(ctx context.Context, name string) (Parody, error) {
	row := q.db.QueryRow(ctx, getParody, name)
	var i Parody
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const getarchiveByParody = `-- name: GetarchiveByParody :many
select
    archive.id,
    archive.title,
    archive.summary,
    archive.language,
    archive.category,
    archive.page_count,
    archive.file_path,
    archive.file_hash,
    archive.thumb_path,
    archive.created_at,
    archive.updated_at,
    archive.release_date,
    reading_progress.page
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = $2
where parody.name = $1
`

type GetarchiveByParodyParams struct {
	Name string    `json:"name"`
	Uid  uuid.UUID `json:"uid"`
}

type GetarchiveByParodyRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int16      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileHash    string     `json:"file_hash"`
	ThumbPath   *string    `json:"thumb_path"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int16     `json:"page"`
}

func (q *Queries) GetarchiveByParody(ctx context.Context, arg GetarchiveByParodyParams) ([]GetarchiveByParodyRow, error) {
	rows, err := q.db.Query(ctx, getarchiveByParody, arg.Name, arg.Uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetarchiveByParodyRow
	for rows.Next() {
		var i GetarchiveByParodyRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileHash,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parodyExists = `-- name: ParodyExists :execresult
select id, name
from parody
where name = $1
`

func (q *Queries) ParodyExists(ctx context.Context, name string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, parodyExists, name)
}

const removeParodyFromArchive = `-- name: RemoveParodyFromArchive :many
delete from archive_parody
where archive_id = $1
returning
    parody_id,
    (select parody.count from parody where parody.id = archive_parody.parody_id)
`

type RemoveParodyFromArchiveRow struct {
	ParodyID int32 `json:"parody_id"`
	Count    int32 `json:"count"`
}

func (q *Queries) RemoveParodyFromArchive(ctx context.Context, archiveID string) ([]RemoveParodyFromArchiveRow, error) {
	rows, err := q.db.Query(ctx, removeParodyFromArchive, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemoveParodyFromArchiveRow
	for rows.Next() {
		var i RemoveParodyFromArchiveRow
		if err := rows.Scan(&i.ParodyID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalArchiveWithParody = `-- name: TotalArchiveWithParody :one
select count(archive.id)
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
where parody.name = $1
`

func (q *Queries) TotalArchiveWithParody(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, totalArchiveWithParody, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateParodyCount = `-- name: UpdateParodyCount :exec
update parody
set count = $1
where id = $2
`

type UpdateParodyCountParams struct {
	Count int32 `json:"count"`
	ID    int32 `json:"id"`
}

func (q *Queries) UpdateParodyCount(ctx context.Context, arg UpdateParodyCountParams) error {
	_, err := q.db.Exec(ctx, updateParodyCount, arg.Count, arg.ID)
	return err
}
