// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

/*
import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
insert into sessions (
  session_id,
  user_id,
  token,
  expires_at,
  created_at,
  ip_address,
  user_agent
) values ( $1, $2, $3, $4, $5,  $6, $7 )
`

type CreateSessionParams struct {
	SessionID uuid.UUID   `json:"session_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Token     string      `json:"token"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedAt time.Time   `json:"created_at"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent *string     `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.SessionID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions
where token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getSession = `-- name: GetSession :one
select session_id, user_id, token, expires_at, created_at, ip_address, user_agent
from sessions
where token = $1
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
select users.id, users.name, sessions.expires_at
from users
join sessions on users.id = sessions.user_id
where sessions.token = $1
`

type GetUserByTokenRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetUserByToken(ctx context.Context, token string) (GetUserByTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByToken, token)
	var i GetUserByTokenRow
	err := row.Scan(&i.ID, &i.Name, &i.ExpiresAt)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
select session_id, user_id, token, expires_at, created_at, ip_address, user_agent
from sessions
where user_id = $1
`

func (q *Queries) GetUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.Token,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.IpAddress,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
*/
