// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const archiveUrlExists = `-- name: ArchiveUrlExists :execresult
select url
from archive_url
where url = $1
`

func (q *Queries) ArchiveUrlExists(ctx context.Context, url string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, archiveUrlExists, url)
}

const createArchiveURL = `-- name: CreateArchiveURL :exec
insert into archive_url (url, archive_id)
values ($1, $2)
`

type CreateArchiveURLParams struct {
	Url       string  `json:"url"`
	ArchiveID *string `json:"archive_id"`
}

func (q *Queries) CreateArchiveURL(ctx context.Context, arg CreateArchiveURLParams) error {
	_, err := q.db.Exec(ctx, createArchiveURL, arg.Url, arg.ArchiveID)
	return err
}

const getArchiveUrls = `-- name: GetArchiveUrls :many
select archive_url.id, archive_url.url
from archive
join archive_url on archive.id = archive_url.archive_id
where archive.id = $1
`

type GetArchiveUrlsRow struct {
	ID  int32  `json:"id"`
	Url string `json:"url"`
}

func (q *Queries) GetArchiveUrls(ctx context.Context, id string) ([]GetArchiveUrlsRow, error) {
	rows, err := q.db.Query(ctx, getArchiveUrls, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveUrlsRow
	for rows.Next() {
		var i GetArchiveUrlsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArchiveUrl = `-- name: RemoveArchiveUrl :exec
delete from archive_url
where archive_id = $1
`

func (q *Queries) RemoveArchiveUrl(ctx context.Context, archiveID *string) error {
	_, err := q.db.Exec(ctx, removeArchiveUrl, archiveID)
	return err
}
