// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const archiveUrlExists = `-- name: ArchiveUrlExists :execresult
select url
from archive_url
where url = $1
`

func (q *Queries) ArchiveUrlExists(ctx context.Context, url string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, archiveUrlExists, url)
}

const bulkAddArchiveURLs = `-- name: BulkAddArchiveURLs :exec
insert into archive_url (archive_id, url)
select $1, unnest($2::text[])
`

type BulkAddArchiveURLsParams struct {
	ArchiveID string   `json:"archive_id"`
	Urls      []string `json:"urls"`
}

func (q *Queries) BulkAddArchiveURLs(ctx context.Context, arg BulkAddArchiveURLsParams) error {
	_, err := q.db.Exec(ctx, bulkAddArchiveURLs, arg.ArchiveID, arg.Urls)
	return err
}

const createArchiveURL = `-- name: CreateArchiveURL :exec
insert into archive_url (url, archive_id)
values ($1, $2)
`

type CreateArchiveURLParams struct {
	Url       string `json:"url"`
	ArchiveID string `json:"archive_id"`
}

func (q *Queries) CreateArchiveURL(ctx context.Context, arg CreateArchiveURLParams) error {
	_, err := q.db.Exec(ctx, createArchiveURL, arg.Url, arg.ArchiveID)
	return err
}

const getArchiveUrlIDs = `-- name: GetArchiveUrlIDs :many
select id 
from archive_url
where archive_id = $1
`

func (q *Queries) GetArchiveUrlIDs(ctx context.Context, archiveID string) ([]int32, error) {
	rows, err := q.db.Query(ctx, getArchiveUrlIDs, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveUrls = `-- name: GetArchiveUrls :many
select id, url
from archive_url
where archive_id = $1
`

type GetArchiveUrlsRow struct {
	ID  int32  `json:"id"`
	Url string `json:"url"`
}

func (q *Queries) GetArchiveUrls(ctx context.Context, archiveID string) ([]GetArchiveUrlsRow, error) {
	rows, err := q.db.Query(ctx, getArchiveUrls, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveUrlsRow
	for rows.Next() {
		var i GetArchiveUrlsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArchiveUrl = `-- name: RemoveArchiveUrl :exec
delete from archive_url
where archive_id = $1 and url = any($2::text[])
`

type RemoveArchiveUrlParams struct {
	ArchiveID string   `json:"archive_id"`
	Urls      []string `json:"urls"`
}

func (q *Queries) RemoveArchiveUrl(ctx context.Context, arg RemoveArchiveUrlParams) error {
	_, err := q.db.Exec(ctx, removeArchiveUrl, arg.ArchiveID, arg.Urls)
	return err
}
