package config

type Sources struct {
	Remote []*Source
	Local  []*Source
}

type Source struct {
	Enabled bool
	Name    string
	Type    string
	File    string
	API     string
}

const (

	// Sources
	SourceNhentai   = "nhentai"
	SourceComicInfo = "comicinfo"
	SourceForm      = "form"
	SourceHentag    = "hentag"

	// Metadata Files
	ComicInfoFile = "ComicInfo.xml"
	HentagFile    = "info.json"
	NHFile        = "info.txt"

	// Source Specific
	// nhentai
	NHApi = "https://nhentai.net/api"
)

var (
	// Methods
	MethodID    = "id"
	MethodTitle = "title"

	// Metadata
	MetadataFormats = map[string]string{
		SourceComicInfo: ComicInfoFile,
		SourceHentag:    HentagFile,
		SourceNhentai:   NHFile,
	}

	NHFileTypes = map[string]string{
		"w": ".webp",
		"j": ".jpg",
		"p": ".png",
	}
)

func initRemoteSources() []*Source {
	sourceType := "remote"
	sources := []*Source{}

	nhentai := Source{
		Enabled: false,
		Name:    "nhentai",
		Type:    sourceType,
		File:    "info.txt", // Generated by https://github.com/RicterZ/nhentai
		API:     "https://nhentai.net/api",
	}
	sources = append(sources, &nhentai)

	return sources
}

func initLocalSources() []*Source {
	sourceType := "local"
	sources := []*Source{}

	comicinfo := Source{
		Enabled: false,
		Name:    "comicinfo",
		Type:    sourceType,
		File:    "ComicInfo.xml",
		API:     "",
	}
	sources = append(sources, &comicinfo)

	return sources
}

func InitSources() *Sources {
	remote := initRemoteSources()
	local := initLocalSources()

	return &Sources{
		Remote: remote,
		Local:  local,
	}
}

func (s *Sources) ToMap(sources ...[]*Source) map[string]*Source {
	m := make(map[string]*Source)

	for _, t := range sources {
		for _, source := range t {
			m[source.Name] = source
		}
	}

	return m
}

func (s *Sources) EnableDefault(cfg *Config) {
	sources := s.ToMap(s.Remote, s.Local)

	for _, toEnable := range cfg.Metadata.EnabledSources {
		sources[toEnable].Enabled = true
	}
}

func (s *Sources) GetEnabledSources() *Sources {
	remoteEnabled := []*Source{}
	for _, source := range s.Remote {
		if source.Enabled {
			remoteEnabled = append(remoteEnabled, source)
		}
	}

	localEnabled := []*Source{}
	for _, source := range s.Local {
		if source.Enabled {
			localEnabled = append(localEnabled, source)
		}
	}

	return &Sources{
		Remote: remoteEnabled,
		Local:  localEnabled,
	}
}
