import { sql } from 'drizzle-orm';
import { index, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';
import { user } from './auth.schema';
import type { ThemeTokens } from '$lib/themes/tokens';

export const task = sqliteTable('task', {
	id: text('id')
		.primaryKey()
		.$defaultFn(() => crypto.randomUUID()),
	title: text('title').notNull(),
	priority: integer('priority').notNull().default(1)
});

// Theme tables live here, not in auth.schema.ts - that file is regenerated by
// `bun run auth:schema` and would clobber additions. The Go backend never reads
// these; they are a pure frontend concern.

export const userTheme = sqliteTable(
	'user_theme',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		name: text('name').notNull(),
		appearance: text('appearance', { enum: ['light', 'dark'] }).notNull(),
		tokens: text('tokens', { mode: 'json' }).notNull().$type<ThemeTokens>(),
		createdAt: integer('created_at', { mode: 'timestamp_ms' })
			.default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
			.notNull(),
		updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
			.default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
			.$onUpdate(() => new Date())
			.notNull()
	},
	(table) => [index('user_theme_userId_idx').on(table.userId)]
);

// Missing row = "never customized", the same lazy-row convention the backend
// uses for reader_settings.
export const userPreferences = sqliteTable('user_preferences', {
	userId: text('user_id')
		.primaryKey()
		.references(() => user.id, { onDelete: 'cascade' }),
	themeId: text('theme_id').notNull().default('shoka-dark'),
	updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
		.default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
		.$onUpdate(() => new Date())
		.notNull()
});

export * from './auth.schema';
