// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const categoryExists = `-- name: CategoryExists :execresult
;

select category
from archive
where category = ?
`

func (q *Queries) CategoryExists(ctx context.Context, category *string) (sql.Result, error) {
	return q.db.ExecContext(ctx, categoryExists, category)
}

const getAllCategory = `-- name: GetAllCategory :many
select distinct category
from archive
where category is not null
order by category
`

func (q *Queries) GetAllCategory(ctx context.Context) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var category *string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByCategory = `-- name: GetArchiveByCategory :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, reading_progress.page
from archive
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?2
where category = ?
`

type GetArchiveByCategoryParams struct {
	Uid      string  `json:"uid"`
	Category *string `json:"category"`
}

type GetArchiveByCategoryRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchiveByCategory(ctx context.Context, arg GetArchiveByCategoryParams) ([]GetArchiveByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveByCategory, arg.Uid, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByCategoryRow
	for rows.Next() {
		var i GetArchiveByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByCategoryList = `-- name: GetArchiveByCategoryList :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, reading_progress.page
from archive
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?4
where category = ?
order by
    case when sqlc.arg('order_by') = 'title_asc' then archive.title end asc,
    case when sqlc.arg('order_by') = 'title_desc' then archive.title end desc,
    case when sqlc.arg('order_by') = 'page_count_asc' then archive.page_count end asc,
    case when sqlc.arg('order_by') = 'page_count_desc' then archive.page_count end desc,
    case when sqlc.arg('order_by') = 'created_at_asc' then archive.created_at end asc,
    case when sqlc.arg('order_by') = 'created_at_desc' then archive.created_at end desc,
    case when sqlc.arg('order_by') = 'updated_at_asc' then archive.updated_at end asc,
    case when sqlc.arg('order_by') = 'updated_at_desc' then archive.updated_at end desc,
    case
        when sqlc.arg('order_by') = 'release_date_asc' then archive.release_date
    end asc,
    case
        when sqlc.arg('order_by') = 'release_date_desc' then archive.relase_date
    end desc,
    case when sqlc.arg('order_by') = 'last_read_asc' then reading_progress.last_read end asc,
    case when sqlc.arg('order_by') = 'last_read_desc' then reading_progress.last_read end desc
limit ?
offset ?
`

type GetArchiveByCategoryListParams struct {
	Uid      string  `json:"uid"`
	Category *string `json:"category"`
	Limit    int64   `json:"limit"`
	Offset   int64   `json:"offset"`
}

type GetArchiveByCategoryListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchiveByCategoryList(ctx context.Context, arg GetArchiveByCategoryListParams) ([]GetArchiveByCategoryListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveByCategoryList,
		arg.Uid,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByCategoryListRow
	for rows.Next() {
		var i GetArchiveByCategoryListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByCategories = `-- name: GetArchiveIDsByCategories :many
;

select archive.id
from archive
where category in (/*SLICE:categories*/?)
group by archive.id
having count(distinct archive.id) = ?2
`

type GetArchiveIDsByCategoriesParams struct {
	Categories []*string `json:"categories"`
	Amount     string    `json:"amount"`
}

func (q *Queries) GetArchiveIDsByCategories(ctx context.Context, arg GetArchiveIDsByCategoriesParams) ([]string, error) {
	query := getArchiveIDsByCategories
	var queryParams []interface{}
	if len(arg.Categories) > 0 {
		for _, v := range arg.Categories {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:categories*/?", strings.Repeat(",?", len(arg.Categories))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:categories*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Amount)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByCategory = `-- name: GetArchiveIDsByCategory :many
;

select archive.id
from archive
where category = ?
`

func (q *Queries) GetArchiveIDsByCategory(ctx context.Context, category *string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveIDsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalArchiveWithCategory = `-- name: TotalArchiveWithCategory :one
;

select count(id)
from archive
where category = ?
`

func (q *Queries) TotalArchiveWithCategory(ctx context.Context, category *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalArchiveWithCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}
