// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: circle.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const bulkAddArchiveCircle = `-- name: BulkAddArchiveCircle :exec
;

insert or ignore into archive_circle (archive_id, circle_id)
select ?, value
from json_each(?2)
`

type BulkAddArchiveCircleParams struct {
	ArchiveID *string     `json:"archive_id"`
	Circle    interface{} `json:"circle"`
}

func (q *Queries) BulkAddArchiveCircle(ctx context.Context, arg BulkAddArchiveCircleParams) error {
	_, err := q.db.ExecContext(ctx, bulkAddArchiveCircle, arg.ArchiveID, arg.Circle)
	return err
}

const bulkAddCircle = `-- name: BulkAddCircle :exec
;

insert or ignore into circle (name, count)
select value, 0
from json_each(?1)
`

func (q *Queries) BulkAddCircle(ctx context.Context, circle interface{}) error {
	_, err := q.db.ExecContext(ctx, bulkAddCircle, circle)
	return err
}

const bulkGetCircle = `-- name: BulkGetCircle :many
;

select id, name
from circle
where name in (/*SLICE:circle*/?)
`

type BulkGetCircleRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) BulkGetCircle(ctx context.Context, circle []string) ([]BulkGetCircleRow, error) {
	query := bulkGetCircle
	var queryParams []interface{}
	if len(circle) > 0 {
		for _, v := range circle {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:circle*/?", strings.Repeat(",?", len(circle))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:circle*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkGetCircleRow
	for rows.Next() {
		var i BulkGetCircleRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkRemoveCircleFromArchive = `-- name: BulkRemoveCircleFromArchive :exec
;

delete from archive_circle
where archive_id = ? and circle_id in (select value from json_each(?2))
`

type BulkRemoveCircleFromArchiveParams struct {
	ArchiveID *string     `json:"archive_id"`
	Circle    interface{} `json:"circle"`
}

func (q *Queries) BulkRemoveCircleFromArchive(ctx context.Context, arg BulkRemoveCircleFromArchiveParams) error {
	_, err := q.db.ExecContext(ctx, bulkRemoveCircleFromArchive, arg.ArchiveID, arg.Circle)
	return err
}

const circleExists = `-- name: CircleExists :execresult
;

select name
from circle
where name = ?
`

func (q *Queries) CircleExists(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, circleExists, name)
}

const createCircle = `-- name: CreateCircle :one
insert into circle (name, count)
values (?, ?)
returning id, name, count
`

type CreateCircleParams struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error) {
	row := q.db.QueryRowContext(ctx, createCircle, arg.Name, arg.Count)
	var i Circle
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const decrementCircleCount = `-- name: DecrementCircleCount :exec
;


update circle
set count = count - 1
where id in (/*SLICE:circles*/?)
`

func (q *Queries) DecrementCircleCount(ctx context.Context, circles []int64) error {
	query := decrementCircleCount
	var queryParams []interface{}
	if len(circles) > 0 {
		for _, v := range circles {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:circles*/?", strings.Repeat(",?", len(circles))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:circles*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteCircle = `-- name: DeleteCircle :exec
;

delete from circle
where name = ?
`

func (q *Queries) DeleteCircle(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCircle, name)
	return err
}

const getAllCircle = `-- name: GetAllCircle :many
;

select id, name, count
from circle
order by id
`

func (q *Queries) GetAllCircle(ctx context.Context) ([]Circle, error) {
	rows, err := q.db.QueryContext(ctx, getAllCircle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Circle
	for rows.Next() {
		var i Circle
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveCircleIDs = `-- name: GetArchiveCircleIDs :many
;

select circle.id
from archive
join archive_circle on archive.id = archive_circle.archive_id
join circle on archive_circle.circle_id = circle.id
where archive.id = ?
`

func (q *Queries) GetArchiveCircleIDs(ctx context.Context, id string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveCircleIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCircle = `-- name: GetCircle :one
;

select id, name, count
from circle
where name = ?
`

func (q *Queries) GetCircle(ctx context.Context, name string) (Circle, error) {
	row := q.db.QueryRowContext(ctx, getCircle, name)
	var i Circle
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const getCircleArtists = `-- name: GetCircleArtists :many
;

select artist.id, artist.name, artist.count
from circle
join artist_circle on circle.id = artist_circle.circle_id
join artist on artist_circle.artist_id = artist.id
where circle.name = ?
`

func (q *Queries) GetCircleArtists(ctx context.Context, name string) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, getCircleArtists, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCircleList = `-- name: GetCircleList :many
;

select id, name, count
from circle
order by ?
limit ?
offset ?
`

type GetCircleListParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetCircleList(ctx context.Context, arg GetCircleListParams) ([]Circle, error) {
	rows, err := q.db.QueryContext(ctx, getCircleList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Circle
	for rows.Next() {
		var i Circle
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCircleCount = `-- name: IncrementCircleCount :exec
;

update circle
set count = count + 1
where id in (/*SLICE:circles*/?)
`

func (q *Queries) IncrementCircleCount(ctx context.Context, circles []int64) error {
	query := incrementCircleCount
	var queryParams []interface{}
	if len(circles) > 0 {
		for _, v := range circles {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:circles*/?", strings.Repeat(",?", len(circles))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:circles*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const removeArtistsFromCircle = `-- name: RemoveArtistsFromCircle :exec
;

delete from artist_circle
where circle_id = ?
`

func (q *Queries) RemoveArtistsFromCircle(ctx context.Context, circleID *int64) error {
	_, err := q.db.ExecContext(ctx, removeArtistsFromCircle, circleID)
	return err
}

const totalCircle = `-- name: TotalCircle :one
;

select count(id)
from circle
`

func (q *Queries) TotalCircle(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalCircle)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateCircle = `-- name: UpdateCircle :one
;

update circle
set name = ?
where name = ?2
returning id, name, count
`

type UpdateCircleParams struct {
	Name    string `json:"name"`
	OldName string `json:"old_name"`
}

func (q *Queries) UpdateCircle(ctx context.Context, arg UpdateCircleParams) (Circle, error) {
	row := q.db.QueryRowContext(ctx, updateCircle, arg.Name, arg.OldName)
	var i Circle
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}
