// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package sqlc

import (
	"context"
	"strings"
	"time"
)

const addFavoriteArchive = `-- name: AddFavoriteArchive :exec
insert into favorite_archive (archive_id, user_id, favorited_at)
values (?, ?, datetime('now'))
on conflict (archive_id, user_id) do nothing
`

type AddFavoriteArchiveParams struct {
	ArchiveID string `json:"archive_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) AddFavoriteArchive(ctx context.Context, arg AddFavoriteArchiveParams) error {
	_, err := q.db.ExecContext(ctx, addFavoriteArchive, arg.ArchiveID, arg.UserID)
	return err
}

const archiveIsFavorited = `-- name: ArchiveIsFavorited :one
;

select exists (
    select 1 from favorite_archive where archive_id = ? and user_id = ?2
) = 1
`

type ArchiveIsFavoritedParams struct {
	ArchiveID string `json:"archive_id"`
	Uid       string `json:"uid"`
}

func (q *Queries) ArchiveIsFavorited(ctx context.Context, arg ArchiveIsFavoritedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, archiveIsFavorited, arg.ArchiveID, arg.Uid)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserFavoriteArchive = `-- name: CountUserFavoriteArchive :one
;

select count(*)
from favorite_archive
where user_id = ?
`

func (q *Queries) CountUserFavoriteArchive(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserFavoriteArchive, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFavoritedArchiveIDs = `-- name: GetFavoritedArchiveIDs :many
;

select archive_id
from favorite_archive
where user_id = ?1 and archive_id in (/*SLICE:ids*/?)
`

type GetFavoritedArchiveIDsParams struct {
	Uid string   `json:"uid"`
	Ids []string `json:"ids"`
}

// Bulk existence check used to attach IsFavorited to archive list responses
// without an N+1 query per archive.
func (q *Queries) GetFavoritedArchiveIDs(ctx context.Context, arg GetFavoritedArchiveIDsParams) ([]string, error) {
	query := getFavoritedArchiveIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Uid)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var archive_id string
		if err := rows.Scan(&archive_id); err != nil {
			return nil, err
		}
		items = append(items, archive_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFavoriteArchiveList = `-- name: GetUserFavoriteArchiveList :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, archive.cover_page, reading_progress.page, reading_progress.last_read, reading_progress.completed
from archive
join favorite_archive as fa on archive.id = fa.archive_id
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?1
where fa.user_id = ?1
order by fa.favorited_at desc
limit ?3
offset ?2
`

type GetUserFavoriteArchiveListParams struct {
	Uid    string `json:"uid"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type GetUserFavoriteArchiveListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	CoverPage   int64      `json:"cover_page"`
	Page        *int64     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Completed   *bool      `json:"completed"`
}

func (q *Queries) GetUserFavoriteArchiveList(ctx context.Context, arg GetUserFavoriteArchiveListParams) ([]GetUserFavoriteArchiveListRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFavoriteArchiveList, arg.Uid, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFavoriteArchiveListRow
	for rows.Next() {
		var i GetUserFavoriteArchiveListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.CoverPage,
			&i.Page,
			&i.LastRead,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavoriteArchive = `-- name: RemoveFavoriteArchive :exec
;

delete from favorite_archive
where archive_id = ? and user_id = ?2
`

type RemoveFavoriteArchiveParams struct {
	ArchiveID string `json:"archive_id"`
	Uid       string `json:"uid"`
}

func (q *Queries) RemoveFavoriteArchive(ctx context.Context, arg RemoveFavoriteArchiveParams) error {
	_, err := q.db.ExecContext(ctx, removeFavoriteArchive, arg.ArchiveID, arg.Uid)
	return err
}
