// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filter.sql

package sqlc

import (
	"context"
	"strings"
	"time"
)

const countFilteredArchive = `-- name: CountFilteredArchive :one
;

select count(archive.id)
from archive
where archive.id in (/*SLICE:ids*/?)
`

func (q *Queries) CountFilteredArchive(ctx context.Context, ids []string) (int64, error) {
	query := countFilteredArchive
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArchiveFilter = `-- name: GetArchiveFilter :one
;

select archive.id
from archive
where archive.id in (/*SLICE:ids*/?)
limit ?
offset ?
`

type GetArchiveFilterParams struct {
	Ids    []string `json:"ids"`
	Limit  int64    `json:"limit"`
	Offset int64    `json:"offset"`
}

func (q *Queries) GetArchiveFilter(ctx context.Context, arg GetArchiveFilterParams) (string, error) {
	query := getArchiveFilter
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getArchiveFilterSortList = `-- name: GetArchiveFilterSortList :many
select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, archive.cover_page, reading_progress.page, reading_progress.last_read, reading_progress.completed
from archive
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?3
where archive.id in (/*SLICE:ids*/?)
order by
    case when sqlc.arg('order_by') = 'title_asc' then archive.title end asc,
    case when sqlc.arg('order_by') = 'title_desc' then archive.title end desc,
    case when sqlc.arg('order_by') = 'page_count_asc' then archive.page_count end asc,
    case when sqlc.arg('order_by') = 'page_count_desc' then archive.page_count end desc,
    case when sqlc.arg('order_by') = 'created_at_asc' then archive.created_at end asc,
    case when sqlc.arg('order_by') = 'created_at_desc' then archive.created_at end desc,
    case when sqlc.arg('order_by') = 'updated_at_asc' then archive.updated_at end asc,
    case when sqlc.arg('order_by') = 'updated_at_desc' then archive.updated_at end desc,
    case
        when sqlc.arg('order_by') = 'release_date_asc' then archive.release_date
    end asc,
    case
        when sqlc.arg('order_by') = 'release_date_desc' then archive.release_date
    end desc,
    case when sqlc.arg('order_by') = 'last_read_asc' then reading_progress.last_read end asc,
    case when sqlc.arg('order_by') = 'last_read_desc' then reading_progress.last_read end desc
limit ?
offset ?
`

type GetArchiveFilterSortListParams struct {
	Uid    string   `json:"uid"`
	Ids    []string `json:"ids"`
	Limit  int64    `json:"limit"`
	Offset int64    `json:"offset"`
}

type GetArchiveFilterSortListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	CoverPage   int64      `json:"cover_page"`
	Page        *int64     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Completed   *bool      `json:"completed"`
}

func (q *Queries) GetArchiveFilterSortList(ctx context.Context, arg GetArchiveFilterSortListParams) ([]GetArchiveFilterSortListRow, error) {
	query := getArchiveFilterSortList
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Uid)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveFilterSortListRow
	for rows.Next() {
		var i GetArchiveFilterSortListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.CoverPage,
			&i.Page,
			&i.LastRead,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveSort = `-- name: GetArchiveSort :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, archive.cover_page, reading_progress.page, reading_progress.last_read, reading_progress.completed
from archive
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?1
order by
    case when sqlc.arg('order_by') = 'title_asc' then title end asc,
    case when sqlc.arg('order_by') = 'title_desc' then title end desc,
    case when sqlc.arg('order_by') = 'page_count_asc' then page_count end asc,
    case when sqlc.arg('order_by') = 'page_count_desc' then page_count end desc,
    case when sqlc.arg('order_by') = 'created_at_asc' then created_at end asc,
    case when sqlc.arg('order_by') = 'created_at_desc' then created_at end desc,
    case when sqlc.arg('order_by') = 'updated_at_asc' then updated_at end asc,
    case when sqlc.arg('order_by') = 'updated_at_desc' then updated_at end desc,
    case when sqlc.arg('order_by') = 'release_date_asc' then release_date end asc,
    case when sqlc.arg('order_by') = 'release_date_desc' then release_date end desc,
    case when sqlc.arg('order_by') = 'last_read_asc' then reading_progress.last_read end asc,
    case when sqlc.arg('order_by') = 'last_read_desc' then reading_progress.last_read end desc
`

type GetArchiveSortRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	CoverPage   int64      `json:"cover_page"`
	Page        *int64     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Completed   *bool      `json:"completed"`
}

func (q *Queries) GetArchiveSort(ctx context.Context, uid string) ([]GetArchiveSortRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveSort, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveSortRow
	for rows.Next() {
		var i GetArchiveSortRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.CoverPage,
			&i.Page,
			&i.LastRead,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveSortList = `-- name: GetArchiveSortList :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, archive.cover_page, reading_progress.page, reading_progress.last_read, reading_progress.completed
from archive
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?3
order by
    case when sqlc.arg('order_by') = 'title_asc' then title end asc,
    case when sqlc.arg('order_by') = 'title_desc' then title end desc,
    case when sqlc.arg('order_by') = 'page_count_asc' then page_count end asc,
    case when sqlc.arg('order_by') = 'page_count_desc' then page_count end desc,
    case when sqlc.arg('order_by') = 'created_at_asc' then created_at end asc,
    case when sqlc.arg('order_by') = 'created_at_desc' then created_at end desc,
    case when sqlc.arg('order_by') = 'updated_at_asc' then updated_at end asc,
    case when sqlc.arg('order_by') = 'updated_at_desc' then updated_at end desc,
    case when sqlc.arg('order_by') = 'release_date_asc' then release_date end asc,
    case when sqlc.arg('order_by') = 'release_date_desc' then release_date end desc,
    case when sqlc.arg('order_by') = 'last_read_asc' then reading_progress.last_read end asc,
    case when sqlc.arg('order_by') = 'last_read_desc' then reading_progress.last_read end desc
limit ?
offset ?
`

type GetArchiveSortListParams struct {
	Uid    string `json:"uid"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type GetArchiveSortListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	CoverPage   int64      `json:"cover_page"`
	Page        *int64     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Completed   *bool      `json:"completed"`
}

func (q *Queries) GetArchiveSortList(ctx context.Context, arg GetArchiveSortListParams) ([]GetArchiveSortListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveSortList, arg.Uid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveSortListRow
	for rows.Next() {
		var i GetArchiveSortListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.CoverPage,
			&i.Page,
			&i.LastRead,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
