// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: language.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const getAllLanguage = `-- name: GetAllLanguage :many
select distinct language
from archive
where language is not null
order by language
`

func (q *Queries) GetAllLanguage(ctx context.Context) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, getAllLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var language *string
		if err := rows.Scan(&language); err != nil {
			return nil, err
		}
		items = append(items, language)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByLanguage = `-- name: GetArchiveByLanguage :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, reading_progress.page
from archive
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?2
where language = ?
`

type GetArchiveByLanguageParams struct {
	Uid      string  `json:"uid"`
	Language *string `json:"language"`
}

type GetArchiveByLanguageRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchiveByLanguage(ctx context.Context, arg GetArchiveByLanguageParams) ([]GetArchiveByLanguageRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveByLanguage, arg.Uid, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByLanguageRow
	for rows.Next() {
		var i GetArchiveByLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByLanguageList = `-- name: GetArchiveByLanguageList :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, reading_progress.page
from archive
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?4
where language = ?
order by
    case when sqlc.arg('order_by') = 'title_asc' then archive.title end asc,
    case when sqlc.arg('order_by') = 'title_desc' then archive.title end desc,
    case when sqlc.arg('order_by') = 'page_count_asc' then archive.page_count end asc,
    case when sqlc.arg('order_by') = 'page_count_desc' then archive.page_count end desc,
    case when sqlc.arg('order_by') = 'created_at_asc' then archive.created_at end asc,
    case when sqlc.arg('order_by') = 'created_at_desc' then archive.created_at end desc,
    case when sqlc.arg('order_by') = 'updated_at_asc' then archive.updated_at end asc,
    case when sqlc.arg('order_by') = 'updated_at_desc' then archive.updated_at end desc,
    case
        when sqlc.arg('order_by') = 'release_date_asc' then archive.release_date
    end asc,
    case
        when sqlc.arg('order_by') = 'release_date_desc' then archive.release_date
    end desc,
    case when sqlc.arg('order_by') = 'last_read_asc' then reading_progress.last_read end asc,
    case when sqlc.arg('order_by') = 'last_read_desc' then reading_progress.last_read end desc
limit ?
offset ?
`

type GetArchiveByLanguageListParams struct {
	Uid      string  `json:"uid"`
	Language *string `json:"language"`
	Limit    int64   `json:"limit"`
	Offset   int64   `json:"offset"`
}

type GetArchiveByLanguageListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchiveByLanguageList(ctx context.Context, arg GetArchiveByLanguageListParams) ([]GetArchiveByLanguageListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveByLanguageList,
		arg.Uid,
		arg.Language,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByLanguageListRow
	for rows.Next() {
		var i GetArchiveByLanguageListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByLanguage = `-- name: GetArchiveIDsByLanguage :many
;

select archive.id
from archive
where language = ?
`

func (q *Queries) GetArchiveIDsByLanguage(ctx context.Context, language *string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveIDsByLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByLanguages = `-- name: GetArchiveIDsByLanguages :many
;

select archive.id
from archive
where language in (/*SLICE:languages*/?)
group by archive.id
having count(distinct archive.id) = ?2
`

type GetArchiveIDsByLanguagesParams struct {
	Languages []*string `json:"languages"`
	Amount    string    `json:"amount"`
}

func (q *Queries) GetArchiveIDsByLanguages(ctx context.Context, arg GetArchiveIDsByLanguagesParams) ([]string, error) {
	query := getArchiveIDsByLanguages
	var queryParams []interface{}
	if len(arg.Languages) > 0 {
		for _, v := range arg.Languages {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:languages*/?", strings.Repeat(",?", len(arg.Languages))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:languages*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Amount)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const languageExists = `-- name: LanguageExists :execresult
;

select language
from archive
where language = ?
`

func (q *Queries) LanguageExists(ctx context.Context, language *string) (sql.Result, error) {
	return q.db.ExecContext(ctx, languageExists, language)
}

const totalArchiveWithLanguage = `-- name: TotalArchiveWithLanguage :one
;

select count(id)
from archive
where language = ?
`

func (q *Queries) TotalArchiveWithLanguage(ctx context.Context, language *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalArchiveWithLanguage, language)
	var count int64
	err := row.Scan(&count)
	return count, err
}
