// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package sqlc

import (
	"context"
)

const createLibrary = `-- name: CreateLibrary :one
insert into library (
  id,
  name,
  path,
  type
)
values (?, ?, ?, ?)
returning id, name, path, type, created_at, updated_at, scan_interval_minutes, watch_enabled, last_scanned_at
`

type CreateLibraryParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Path string `json:"path"`
	Type string `json:"type"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, createLibrary,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Type,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScanIntervalMinutes,
		&i.WatchEnabled,
		&i.LastScannedAt,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
delete from library
where id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLibrary, id)
	return err
}

const getLibraryByID = `-- name: GetLibraryByID :one
select id, name, path, type, created_at, updated_at, scan_interval_minutes, watch_enabled, last_scanned_at
from library
where id = ?
`

func (q *Queries) GetLibraryByID(ctx context.Context, id string) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibraryByID, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScanIntervalMinutes,
		&i.WatchEnabled,
		&i.LastScannedAt,
	)
	return i, err
}

const getLibraryByPath = `-- name: GetLibraryByPath :one
;

select id, name, path, type, created_at, updated_at, scan_interval_minutes, watch_enabled, last_scanned_at
from library
where path = ?
`

func (q *Queries) GetLibraryByPath(ctx context.Context, path string) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibraryByPath, path)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScanIntervalMinutes,
		&i.WatchEnabled,
		&i.LastScannedAt,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
;

select id, name, path, type, created_at, updated_at, scan_interval_minutes, watch_enabled, last_scanned_at
from library
order by name
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScanIntervalMinutes,
			&i.WatchEnabled,
			&i.LastScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibrariesDueForScan = `-- name: ListLibrariesDueForScan :many
select id, name, path, type, created_at, updated_at, scan_interval_minutes, watch_enabled, last_scanned_at
from library
where scan_interval_minutes > 0
  and (
    last_scanned_at is null
    or datetime(last_scanned_at, '+' || scan_interval_minutes || ' minutes') <= datetime('now')
  )
order by name
`

// ListLibrariesDueForScan returns every library whose periodic scan is due:
// scanning is enabled (interval > 0) and either it has never been scanned or
// the interval has elapsed since the last scan attempt. Polled by the
// library manager's scheduler.
func (q *Queries) ListLibrariesDueForScan(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibrariesDueForScan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScanIntervalMinutes,
			&i.WatchEnabled,
			&i.LastScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLibraryScanned = `-- name: MarkLibraryScanned :exec
update library
set last_scanned_at = datetime('now')
where id = ?
`

// MarkLibraryScanned records a scan attempt. Deliberately does not touch
// updated_at, which tracks configuration edits rather than scan activity.
func (q *Queries) MarkLibraryScanned(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markLibraryScanned, id)
	return err
}

const updateLibrary = `-- name: UpdateLibrary :one
;

update library
set
    name = ?,
    scan_interval_minutes = ?,
    watch_enabled = ?,
    updated_at = datetime('now')
where id = ?
returning id, name, path, type, created_at, updated_at, scan_interval_minutes, watch_enabled, last_scanned_at
`

type UpdateLibraryParams struct {
	Name                string `json:"name"`
	ScanIntervalMinutes int64  `json:"scan_interval_minutes"`
	WatchEnabled        int64  `json:"watch_enabled"`
	ID                  string `json:"id"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, updateLibrary,
		arg.Name,
		arg.ScanIntervalMinutes,
		arg.WatchEnabled,
		arg.ID,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ScanIntervalMinutes,
		&i.WatchEnabled,
		&i.LastScannedAt,
	)
	return i, err
}
