// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Archive struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
}

type ArchiveArtist struct {
	ArchiveID *string `json:"archive_id"`
	ArtistID  *int64  `json:"artist_id"`
}

type ArchiveCharacter struct {
	ArchiveID   *string `json:"archive_id"`
	CharacterID *int64  `json:"character_id"`
}

type ArchiveParody struct {
	ArchiveID *string `json:"archive_id"`
	ParodyID  *int64  `json:"parody_id"`
}

type ArchiveTag struct {
	ArchiveID *string `json:"archive_id"`
	TagID     *int64  `json:"tag_id"`
}

type ArchiveUrl struct {
	ID        int64  `json:"id"`
	Url       string `json:"url"`
	ArchiveID string `json:"archive_id"`
}

type Artist struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type ArtistAlias struct {
	ID       int64  `json:"id"`
	ArtistID int64  `json:"artist_id"`
	Alias    string `json:"alias"`
}

type ArtistGroup struct {
	ArtistID *int64 `json:"artist_id"`
	GroupID  *int64 `json:"group_id"`
}

type ArtistUrl struct {
	ID       int64  `json:"id"`
	ArtistID int64  `json:"artist_id"`
	Url      string `json:"url"`
}

type Character struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type FavoriteArchive struct {
	ArchiveID   *string   `json:"archive_id"`
	UserID      *string   `json:"user_id"`
	FavoritedAt time.Time `json:"favorited_at"`
}

type Group struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Job struct {
	ID          int64     `json:"id"`
	Type        string    `json:"type"`
	Payload     string    `json:"payload"`
	Status      string    `json:"status"`
	Attempts    int64     `json:"attempts"`
	MaxAttempts int64     `json:"max_attempts"`
	Error       *string   `json:"error"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	RunAfter    time.Time `json:"run_after"`
}

type Parody struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

type ReadingProgress struct {
	ArchiveID *string   `json:"archive_id"`
	UserID    *string   `json:"user_id"`
	Page      int64     `json:"page"`
	Status    string    `json:"status"`
	LastRead  time.Time `json:"last_read"`
}

type Tag struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Count       int64   `json:"count"`
}
