// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parody.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const addParodyToArchive = `-- name: AddParodyToArchive :exec
;

insert into archive_parody (archive_id, parody_id)
values (?, ?)
`

type AddParodyToArchiveParams struct {
	ArchiveID *string `json:"archive_id"`
	ParodyID  *int64  `json:"parody_id"`
}

func (q *Queries) AddParodyToArchive(ctx context.Context, arg AddParodyToArchiveParams) error {
	_, err := q.db.ExecContext(ctx, addParodyToArchive, arg.ArchiveID, arg.ParodyID)
	return err
}

const bulkAddArchiveParodies = `-- name: BulkAddArchiveParodies :exec
;

insert into archive_parody (archive_id, parody_id)
select ?, value 
from json_each(?2)
`

type BulkAddArchiveParodiesParams struct {
	ArchiveID *string     `json:"archive_id"`
	Parodies  interface{} `json:"parodies"`
}

func (q *Queries) BulkAddArchiveParodies(ctx context.Context, arg BulkAddArchiveParodiesParams) error {
	_, err := q.db.ExecContext(ctx, bulkAddArchiveParodies, arg.ArchiveID, arg.Parodies)
	return err
}

const bulkAddParodies = `-- name: BulkAddParodies :exec
;

insert or ignore into parody (name, count)
select value, 0
from json_each(?1)
`

func (q *Queries) BulkAddParodies(ctx context.Context, parodies interface{}) error {
	_, err := q.db.ExecContext(ctx, bulkAddParodies, parodies)
	return err
}

const bulkGetParodies = `-- name: BulkGetParodies :many
;

select id, name
from parody
where name in (/*SLICE:parodies*/?)
`

type BulkGetParodiesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) BulkGetParodies(ctx context.Context, parodies []string) ([]BulkGetParodiesRow, error) {
	query := bulkGetParodies
	var queryParams []interface{}
	if len(parodies) > 0 {
		for _, v := range parodies {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:parodies*/?", strings.Repeat(",?", len(parodies))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:parodies*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkGetParodiesRow
	for rows.Next() {
		var i BulkGetParodiesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkRemoveParodiesFromArchive = `-- name: BulkRemoveParodiesFromArchive :exec
;

delete from archive_parody
where
    archive_id = ? and parody_id in (select value from json_each(?2))
`

type BulkRemoveParodiesFromArchiveParams struct {
	ArchiveID *string     `json:"archive_id"`
	Parodies  interface{} `json:"parodies"`
}

func (q *Queries) BulkRemoveParodiesFromArchive(ctx context.Context, arg BulkRemoveParodiesFromArchiveParams) error {
	_, err := q.db.ExecContext(ctx, bulkRemoveParodiesFromArchive, arg.ArchiveID, arg.Parodies)
	return err
}

const createParody = `-- name: CreateParody :one
insert into parody (name, count)
values (?, ?)
returning id, name, count
`

type CreateParodyParams struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) CreateParody(ctx context.Context, arg CreateParodyParams) (Parody, error) {
	row := q.db.QueryRowContext(ctx, createParody, arg.Name, arg.Count)
	var i Parody
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const decrementParodyCount = `-- name: DecrementParodyCount :exec
;

update parody
set count = count - 1
where id in (/*SLICE:parodies*/?)
`

func (q *Queries) DecrementParodyCount(ctx context.Context, parodies []int64) error {
	query := decrementParodyCount
	var queryParams []interface{}
	if len(parodies) > 0 {
		for _, v := range parodies {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:parodies*/?", strings.Repeat(",?", len(parodies))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:parodies*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteAllParody = `-- name: DeleteAllParody :exec
;

delete from parody
`

func (q *Queries) DeleteAllParody(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllParody)
	return err
}

const deleteParody = `-- name: DeleteParody :exec
;

delete from parody
where id = ?
`

func (q *Queries) DeleteParody(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteParody, id)
	return err
}

const ensureParodyExist = `-- name: EnsureParodyExist :many
;


insert into parody (name, count)
select value, 0 from json_each(?1)
on conflict (name) do update
set name = excluded.name
returning id, name
`

type EnsureParodyExistRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) EnsureParodyExist(ctx context.Context, parodies interface{}) ([]EnsureParodyExistRow, error) {
	rows, err := q.db.QueryContext(ctx, ensureParodyExist, parodies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnsureParodyExistRow
	for rows.Next() {
		var i EnsureParodyExistRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllParody = `-- name: GetAllParody :many
;

select id, name, count
from parody
order by id
`

func (q *Queries) GetAllParody(ctx context.Context) ([]Parody, error) {
	rows, err := q.db.QueryContext(ctx, getAllParody)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parody
	for rows.Next() {
		var i Parody
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByParody = `-- name: GetArchiveByParody :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, reading_progress.page
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = ?2
where parody.name = ?
`

type GetArchiveByParodyParams struct {
	Uid  *string `json:"uid"`
	Name string  `json:"name"`
}

type GetArchiveByParodyRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchiveByParody(ctx context.Context, arg GetArchiveByParodyParams) ([]GetArchiveByParodyRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveByParody, arg.Uid, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByParodyRow
	for rows.Next() {
		var i GetArchiveByParodyRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByParodyList = `-- name: GetArchiveByParodyList :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, reading_progress.page
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
left join
    reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = ?4
where parody.name = ?
order by
    case when sqlc.arg('order_by') = 'title_asc' then archive.title end asc,
    case when sqlc.arg('order_by') = 'title_desc' then archive.title end desc,
    case when sqlc.arg('order_by') = 'page_count_asc' then archive.page_count end asc,
    case when sqlc.arg('order_by') = 'page_count_desc' then archive.page_count end desc,
    case when sqlc.arg('order_by') = 'created_at_asc' then archive.created_at end asc,
    case when sqlc.arg('order_by') = 'created_at_desc' then archive.created_at end desc,
    case when sqlc.arg('order_by') = 'updated_at_asc' then archive.updated_at end asc,
    case when sqlc.arg('order_by') = 'updated_at_desc' then archive.updated_at end desc,
    case
        when sqlc.arg('order_by') = 'release_date_asc' then archive.release_date
    end asc,
    case
        when sqlc.arg('order_by') = 'release_date_desc' then archive.release_date
    end desc,
    case
        when sqlc.arg('order_by') = 'last_read_asc' then reading_progress.last_read
    end asc,
    case
        when sqlc.arg('order_by') = 'last_read_desc' then reading_progress.last_read
    end desc
limit ?
offset ?
`

type GetArchiveByParodyListParams struct {
	Uid    *string `json:"uid"`
	Name   string  `json:"name"`
	Limit  int64   `json:"limit"`
	Offset int64   `json:"offset"`
}

type GetArchiveByParodyListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchiveByParodyList(ctx context.Context, arg GetArchiveByParodyListParams) ([]GetArchiveByParodyListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveByParodyList,
		arg.Uid,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByParodyListRow
	for rows.Next() {
		var i GetArchiveByParodyListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByParodies = `-- name: GetArchiveIDsByParodies :many
;

select archive.id
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
where parody.name in (/*SLICE:parodies*/?)
group by archive.id
having count(distinct parody.id) = ?2
`

type GetArchiveIDsByParodiesParams struct {
	Parodies []string `json:"parodies"`
	Amount   int64    `json:"amount"`
}

func (q *Queries) GetArchiveIDsByParodies(ctx context.Context, arg GetArchiveIDsByParodiesParams) ([]string, error) {
	query := getArchiveIDsByParodies
	var queryParams []interface{}
	if len(arg.Parodies) > 0 {
		for _, v := range arg.Parodies {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:parodies*/?", strings.Repeat(",?", len(arg.Parodies))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:parodies*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Amount)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByParody = `-- name: GetArchiveIDsByParody :many
;

select archive.id
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
where parody.name = ?
`

func (q *Queries) GetArchiveIDsByParody(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveIDsByParody, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveParody = `-- name: GetArchiveParody :many
;

select parody.id, parody.name, parody.count
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
where archive.id = ?
`

func (q *Queries) GetArchiveParody(ctx context.Context, id string) ([]Parody, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveParody, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parody
	for rows.Next() {
		var i Parody
		if err := rows.Scan(&i.ID, &i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveParodyIDs = `-- name: GetArchiveParodyIDs :many
;

select parody.id
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
where archive.id = ?
`

func (q *Queries) GetArchiveParodyIDs(ctx context.Context, id string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveParodyIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParody = `-- name: GetParody :one
;

select id, name, count
from parody
where name = ?
`

func (q *Queries) GetParody(ctx context.Context, name string) (Parody, error) {
	row := q.db.QueryRowContext(ctx, getParody, name)
	var i Parody
	err := row.Scan(&i.ID, &i.Name, &i.Count)
	return i, err
}

const incrementParodyCount = `-- name: IncrementParodyCount :exec
;

update parody
set count = count + 1
where id in (/*SLICE:parodies*/?)
`

func (q *Queries) IncrementParodyCount(ctx context.Context, parodies []int64) error {
	query := incrementParodyCount
	var queryParams []interface{}
	if len(parodies) > 0 {
		for _, v := range parodies {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:parodies*/?", strings.Repeat(",?", len(parodies))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:parodies*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const parodyExists = `-- name: ParodyExists :execresult
;

select id, name
from parody
where name = ?
`

func (q *Queries) ParodyExists(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, parodyExists, name)
}

const removeParodyFromArchive = `-- name: RemoveParodyFromArchive :exec
;

delete from archive_parody
where archive_id = ? and parody_id in (/*SLICE:parodies*/?)
`

type RemoveParodyFromArchiveParams struct {
	ArchiveID *string  `json:"archive_id"`
	Parodies  []*int64 `json:"parodies"`
}

func (q *Queries) RemoveParodyFromArchive(ctx context.Context, arg RemoveParodyFromArchiveParams) error {
	query := removeParodyFromArchive
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ArchiveID)
	if len(arg.Parodies) > 0 {
		for _, v := range arg.Parodies {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:parodies*/?", strings.Repeat(",?", len(arg.Parodies))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:parodies*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const totalArchiveWithParody = `-- name: TotalArchiveWithParody :one
;

select count(archive.id)
from archive
join archive_parody on archive.id = archive_parody.archive_id
join parody on archive_parody.parody_id = parody.id
where parody.name = ?
`

func (q *Queries) TotalArchiveWithParody(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalArchiveWithParody, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
