// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteReadingProgress = `-- name: DeleteReadingProgress :exec
;

delete from reading_progress
where archive_id = ? and user_id = ?
`

type DeleteReadingProgressParams struct {
	ArchiveID *string `json:"archive_id"`
	UserID    *string `json:"user_id"`
}

func (q *Queries) DeleteReadingProgress(ctx context.Context, arg DeleteReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, deleteReadingProgress, arg.ArchiveID, arg.UserID)
	return err
}

const getAllLastRead = `-- name: GetAllLastRead :many
;

select archive_id, last_read
from reading_progress
`

type GetAllLastReadRow struct {
	ArchiveID *string   `json:"archive_id"`
	LastRead  time.Time `json:"last_read"`
}

func (q *Queries) GetAllLastRead(ctx context.Context) ([]GetAllLastReadRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLastRead)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLastReadRow
	for rows.Next() {
		var i GetAllLastReadRow
		if err := rows.Scan(&i.ArchiveID, &i.LastRead); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReadingProgress = `-- name: GetUserReadingProgress :one
;

select archive_id, user_id, page, status, last_read
from reading_progress
where archive_id = ? and user_id = ?
`

type GetUserReadingProgressParams struct {
	ArchiveID *string `json:"archive_id"`
	UserID    *string `json:"user_id"`
}

func (q *Queries) GetUserReadingProgress(ctx context.Context, arg GetUserReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getUserReadingProgress, arg.ArchiveID, arg.UserID)
	var i ReadingProgress
	err := row.Scan(
		&i.ArchiveID,
		&i.UserID,
		&i.Page,
		&i.Status,
		&i.LastRead,
	)
	return i, err
}

const insertReadingProgress = `-- name: InsertReadingProgress :exec
insert into reading_progress (
  archive_id,
  user_id,
  page,
  status,
  last_read
) values ( ?, ?, ?, ?, ? )
`

type InsertReadingProgressParams struct {
	ArchiveID *string   `json:"archive_id"`
	UserID    *string   `json:"user_id"`
	Page      int64     `json:"page"`
	Status    string    `json:"status"`
	LastRead  time.Time `json:"last_read"`
}

func (q *Queries) InsertReadingProgress(ctx context.Context, arg InsertReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, insertReadingProgress,
		arg.ArchiveID,
		arg.UserID,
		arg.Page,
		arg.Status,
		arg.LastRead,
	)
	return err
}

const updateReadingProgress = `-- name: UpdateReadingProgress :one
;

update reading_progress
set page = coalesce(?4, page),
    status = coalesce(?5, status),
    last_read = coalesce(?, last_read)
where archive_id = ? AND user_id = ?
returning
  archive_id,
  user_id,
  page,
  status,
  last_read
`

type UpdateReadingProgressParams struct {
	Page      int64     `json:"page"`
	Status    string    `json:"status"`
	LastRead  time.Time `json:"last_read"`
	ArchiveID *string   `json:"archive_id"`
	UserID    *string   `json:"user_id"`
}

func (q *Queries) UpdateReadingProgress(ctx context.Context, arg UpdateReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, updateReadingProgress,
		arg.Page,
		arg.Status,
		arg.LastRead,
		arg.ArchiveID,
		arg.UserID,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.ArchiveID,
		&i.UserID,
		&i.Page,
		&i.Status,
		&i.LastRead,
	)
	return i, err
}

const userReadingProgressExists = `-- name: UserReadingProgressExists :execresult
;

select archive_id, user_id, page, status, last_read
from reading_progress
where archive_id = ? and user_id = ?
`

type UserReadingProgressExistsParams struct {
	ArchiveID *string `json:"archive_id"`
	UserID    *string `json:"user_id"`
}

func (q *Queries) UserReadingProgressExists(ctx context.Context, arg UserReadingProgressExistsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, userReadingProgressExists, arg.ArchiveID, arg.UserID)
}
