// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"
	"time"
)

const deleteReadingProgress = `-- name: DeleteReadingProgress :exec
;

delete from progress
where archive_id = ? and user_id = ?
`

type DeleteReadingProgressParams struct {
	ArchiveID string `json:"archive_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteReadingProgress(ctx context.Context, arg DeleteReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, deleteReadingProgress, arg.ArchiveID, arg.UserID)
	return err
}

const getAllLastRead = `-- name: GetAllLastRead :many
;

select archive_id, last_read
from progress
`

type GetAllLastReadRow struct {
	ArchiveID string    `json:"archive_id"`
	LastRead  time.Time `json:"last_read"`
}

func (q *Queries) GetAllLastRead(ctx context.Context) ([]GetAllLastReadRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLastRead)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLastReadRow
	for rows.Next() {
		var i GetAllLastReadRow
		if err := rows.Scan(&i.ArchiveID, &i.LastRead); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgressForArchive = `-- name: GetProgressForArchive :one
;

select archive_id, user_id, page, completed, last_read
from progress
where archive_id = ? and user_id = ?
`

type GetProgressForArchiveParams struct {
	ArchiveID string `json:"archive_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetProgressForArchive(ctx context.Context, arg GetProgressForArchiveParams) (Progress, error) {
	row := q.db.QueryRowContext(ctx, getProgressForArchive, arg.ArchiveID, arg.UserID)
	var i Progress
	err := row.Scan(
		&i.ArchiveID,
		&i.UserID,
		&i.Page,
		&i.Completed,
		&i.LastRead,
	)
	return i, err
}

const insertReadingProgress = `-- name: InsertReadingProgress :exec
insert into progress (
  archive_id,
  user_id,
  page,
  completed,
  last_read
) values ( ?, ?, ?, ?, ? )
`

type InsertReadingProgressParams struct {
	ArchiveID string    `json:"archive_id"`
	UserID    string    `json:"user_id"`
	Page      int64     `json:"page"`
	Completed bool      `json:"completed"`
	LastRead  time.Time `json:"last_read"`
}

func (q *Queries) InsertReadingProgress(ctx context.Context, arg InsertReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, insertReadingProgress,
		arg.ArchiveID,
		arg.UserID,
		arg.Page,
		arg.Completed,
		arg.LastRead,
	)
	return err
}

const updateReadingProgress = `-- name: UpdateReadingProgress :one
;

update progress
set page = coalesce(?4, page),
    completed = coalesce(?5, completed),
    last_read = coalesce(?, last_read)
where archive_id = ? AND user_id = ?
returning
  archive_id,
  user_id,
  page,
  completed,
  last_read
`

type UpdateReadingProgressParams struct {
	Page      int64     `json:"page"`
	Completed bool      `json:"completed"`
	LastRead  time.Time `json:"last_read"`
	ArchiveID string    `json:"archive_id"`
	UserID    string    `json:"user_id"`
}

func (q *Queries) UpdateReadingProgress(ctx context.Context, arg UpdateReadingProgressParams) (Progress, error) {
	row := q.db.QueryRowContext(ctx, updateReadingProgress,
		arg.Page,
		arg.Completed,
		arg.LastRead,
		arg.ArchiveID,
		arg.UserID,
	)
	var i Progress
	err := row.Scan(
		&i.ArchiveID,
		&i.UserID,
		&i.Page,
		&i.Completed,
		&i.LastRead,
	)
	return i, err
}
