// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reader_settings.sql

package sqlc

import (
	"context"
)

const getReaderSettings = `-- name: GetReaderSettings :one
select user_id, reading_direction, page_layout, fit_mode, background, view_mode
from reader_settings
where user_id = ?
`

func (q *Queries) GetReaderSettings(ctx context.Context, userID string) (ReaderSetting, error) {
	row := q.db.QueryRowContext(ctx, getReaderSettings, userID)
	var i ReaderSetting
	err := row.Scan(
		&i.UserID,
		&i.ReadingDirection,
		&i.PageLayout,
		&i.FitMode,
		&i.Background,
		&i.ViewMode,
	)
	return i, err
}

const upsertReaderSettings = `-- name: UpsertReaderSettings :one
;

insert into reader_settings (
  user_id,
  reading_direction,
  page_layout,
  fit_mode,
  background,
  view_mode
) values ( ?, ?, ?, ?, ?, ? )
on conflict (user_id) do update set
  reading_direction = excluded.reading_direction,
  page_layout = excluded.page_layout,
  fit_mode = excluded.fit_mode,
  background = excluded.background,
  view_mode = excluded.view_mode
returning user_id, reading_direction, page_layout, fit_mode, background, view_mode
`

type UpsertReaderSettingsParams struct {
	UserID           string `json:"user_id"`
	ReadingDirection string `json:"reading_direction"`
	PageLayout       string `json:"page_layout"`
	FitMode          string `json:"fit_mode"`
	Background       string `json:"background"`
	ViewMode         string `json:"view_mode"`
}

func (q *Queries) UpsertReaderSettings(ctx context.Context, arg UpsertReaderSettingsParams) (ReaderSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertReaderSettings,
		arg.UserID,
		arg.ReadingDirection,
		arg.PageLayout,
		arg.FitMode,
		arg.Background,
		arg.ViewMode,
	)
	var i ReaderSetting
	err := row.Scan(
		&i.UserID,
		&i.ReadingDirection,
		&i.PageLayout,
		&i.FitMode,
		&i.Background,
		&i.ViewMode,
	)
	return i, err
}
