// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading_progress.sql

package sqlc

import (
	"context"
	"time"
)

const countRecentlyReadArchives = `-- name: CountRecentlyReadArchives :one
;

select count(*)
from reading_progress
where user_id = ?
`

func (q *Queries) CountRecentlyReadArchives(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentlyReadArchives, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteReadingProgress = `-- name: DeleteReadingProgress :exec
;

delete from reading_progress
where archive_id = ? and user_id = ?
`

type DeleteReadingProgressParams struct {
	ArchiveID string `json:"archive_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteReadingProgress(ctx context.Context, arg DeleteReadingProgressParams) error {
	_, err := q.db.ExecContext(ctx, deleteReadingProgress, arg.ArchiveID, arg.UserID)
	return err
}

const getProgressForArchive = `-- name: GetProgressForArchive :one
;

select archive_id, user_id, page, completed, last_read
from reading_progress
where archive_id = ? and user_id = ?
`

type GetProgressForArchiveParams struct {
	ArchiveID string `json:"archive_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetProgressForArchive(ctx context.Context, arg GetProgressForArchiveParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getProgressForArchive, arg.ArchiveID, arg.UserID)
	var i ReadingProgress
	err := row.Scan(
		&i.ArchiveID,
		&i.UserID,
		&i.Page,
		&i.Completed,
		&i.LastRead,
	)
	return i, err
}

const getRecentlyReadArchives = `-- name: GetRecentlyReadArchives :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, reading_progress.page, reading_progress.last_read, reading_progress.completed
from archive
join reading_progress
    on archive.id = reading_progress.archive_id
    and reading_progress.user_id = ?1
order by reading_progress.last_read desc
limit ?3
offset ?2
`

type GetRecentlyReadArchivesParams struct {
	Uid    string `json:"uid"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type GetRecentlyReadArchivesRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	Page        int64      `json:"page"`
	LastRead    time.Time  `json:"last_read"`
	Completed   bool       `json:"completed"`
}

// Deliberately NOT scoped to a library: this is a continue-reading feed
// spanning the whole collection, regardless of which library each archive
// belongs to.
func (q *Queries) GetRecentlyReadArchives(ctx context.Context, arg GetRecentlyReadArchivesParams) ([]GetRecentlyReadArchivesRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentlyReadArchives, arg.Uid, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyReadArchivesRow
	for rows.Next() {
		var i GetRecentlyReadArchivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.Page,
			&i.LastRead,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :one
insert into reading_progress (archive_id, user_id, page, completed, last_read)
values (?, ?, ?, ?, datetime('now'))
on conflict (user_id, archive_id) do update set
    page = excluded.page,
    completed = excluded.completed,
    last_read = excluded.last_read
returning archive_id, user_id, page, completed, last_read
`

type UpsertReadingProgressParams struct {
	ArchiveID string `json:"archive_id"`
	UserID    string `json:"user_id"`
	Page      int64  `json:"page"`
	Completed bool   `json:"completed"`
}

// Idempotent upsert backing PUT /api/archives/{id}/progress. The client
// reports its current absolute page on every page turn, so an insert-or-
// update on the (user_id, archive_id) primary key covers both the create
// and update case with no separate write path needed at the API layer.
func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertReadingProgress,
		arg.ArchiveID,
		arg.UserID,
		arg.Page,
		arg.Completed,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.ArchiveID,
		&i.UserID,
		&i.Page,
		&i.Completed,
		&i.LastRead,
	)
	return i, err
}
