// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const addTagToArchive = `-- name: AddTagToArchive :exec
;

insert into archive_tag (archive_id, tag_id)
values (?, ?)
`

type AddTagToArchiveParams struct {
	ArchiveID *string `json:"archive_id"`
	TagID     *int64  `json:"tag_id"`
}

func (q *Queries) AddTagToArchive(ctx context.Context, arg AddTagToArchiveParams) error {
	_, err := q.db.ExecContext(ctx, addTagToArchive, arg.ArchiveID, arg.TagID)
	return err
}

const bulkAddArchiveTags = `-- name: BulkAddArchiveTags :exec
;

insert or ignore into archive_tag (archive_id, tag_id)
select ?, value
from json_each(?2)
`

type BulkAddArchiveTagsParams struct {
	ArchiveID *string     `json:"archive_id"`
	Tags      interface{} `json:"tags"`
}

func (q *Queries) BulkAddArchiveTags(ctx context.Context, arg BulkAddArchiveTagsParams) error {
	_, err := q.db.ExecContext(ctx, bulkAddArchiveTags, arg.ArchiveID, arg.Tags)
	return err
}

const bulkAddTags = `-- name: BulkAddTags :exec
;

insert or ignore into tag (name, count)
select value, 0
from json_each(?1)
`

func (q *Queries) BulkAddTags(ctx context.Context, tags interface{}) error {
	_, err := q.db.ExecContext(ctx, bulkAddTags, tags)
	return err
}

const bulkGetTags = `-- name: BulkGetTags :many
;

select id, name
from tag
where name in (/*SLICE:tags*/?)
`

type BulkGetTagsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) BulkGetTags(ctx context.Context, tags []string) ([]BulkGetTagsRow, error) {
	query := bulkGetTags
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkGetTagsRow
	for rows.Next() {
		var i BulkGetTagsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkRemoveTagFromArchive = `-- name: BulkRemoveTagFromArchive :exec
;

delete from archive_tag
where archive_id = ? and tag_id in (select value from json_each(?2))
`

type BulkRemoveTagFromArchiveParams struct {
	ArchiveID *string     `json:"archive_id"`
	Tags      interface{} `json:"tags"`
}

func (q *Queries) BulkRemoveTagFromArchive(ctx context.Context, arg BulkRemoveTagFromArchiveParams) error {
	_, err := q.db.ExecContext(ctx, bulkRemoveTagFromArchive, arg.ArchiveID, arg.Tags)
	return err
}

const countTags = `-- name: CountTags :one
;

select count(*) from tag
`

func (q *Queries) CountTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
insert into tag (name, count)
values (?, ?)
returning id, name, description, count
`

type CreateTagParams struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.Count)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Count,
	)
	return i, err
}

const decrementTagCount = `-- name: DecrementTagCount :exec
;

update tag
set count = count - 1
where id in (/*SLICE:tags*/?)
`

func (q *Queries) DecrementTagCount(ctx context.Context, tags []int64) error {
	query := decrementTagCount
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteAllTag = `-- name: DeleteAllTag :exec
;

delete from tag
`

func (q *Queries) DeleteAllTag(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTag)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
;

delete from tag
where id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const ensureTagExist = `-- name: EnsureTagExist :many
;

insert into tag (name, count)
select value, 0 from json_each(?1)
on conflict (name) do update
set name = excluded.name
returning id, name
`

type EnsureTagExistRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) EnsureTagExist(ctx context.Context, tags interface{}) ([]EnsureTagExistRow, error) {
	rows, err := q.db.QueryContext(ctx, ensureTagExist, tags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnsureTagExistRow
	for rows.Next() {
		var i EnsureTagExistRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTags = `-- name: GetAllTags :many
;

select id, name, description, count
from tag
order by name
`

func (q *Queries) GetAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByTag = `-- name: GetArchiveByTag :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, archive.cover_page, reading_progress.page
from archive
join archive_tag on archive.id = archive_tag.archive_id
join tag on archive_tag.tag_id = tag.id
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?2
where tag.name = ?
`

type GetArchiveByTagParams struct {
	Uid  string `json:"uid"`
	Name string `json:"name"`
}

type GetArchiveByTagRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	CoverPage   int64      `json:"cover_page"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchiveByTag(ctx context.Context, arg GetArchiveByTagParams) ([]GetArchiveByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveByTag, arg.Uid, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByTagRow
	for rows.Next() {
		var i GetArchiveByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.CoverPage,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveByTagList = `-- name: GetArchiveByTagList :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, archive.cover_page, reading_progress.page
from archive
join archive_tag on archive.id = archive_tag.archive_id
join tag on archive_tag.tag_id = tag.id
left join
    reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?4
where tag.name = ?
order by
    case when sqlc.arg('order_by') = 'title_asc' then archive.title end asc,
    case when sqlc.arg('order_by') = 'title_desc' then archive.title end desc,
    case when sqlc.arg('order_by') = 'page_count_asc' then archive.page_count end asc,
    case when sqlc.arg('order_by') = 'page_count_desc' then archive.page_count end desc,
    case when sqlc.arg('order_by') = 'created_at_asc' then archive.created_at end asc,
    case when sqlc.arg('order_by') = 'created_at_desc' then archive.created_at end desc,
    case when sqlc.arg('order_by') = 'updated_at_asc' then archive.updated_at end asc,
    case when sqlc.arg('order_by') = 'updated_at_desc' then archive.updated_at end desc,
    case
        when sqlc.arg('order_by') = 'release_date_asc' then archive.release_date
    end asc,
    case
        when sqlc.arg('order_by') = 'release_date_desc' then archive.release_date
    end desc,
    case when sqlc.arg('order_by') = 'last_read_asc' then reading_progress.last_read end asc,
    case when sqlc.arg('order_by') = 'last_read_desc' then reading_progress.last_read end desc
limit ?
offset ?
`

type GetArchiveByTagListParams struct {
	Uid    string `json:"uid"`
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type GetArchiveByTagListRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	CoverPage   int64      `json:"cover_page"`
	Page        *int64     `json:"page"`
}

func (q *Queries) GetArchiveByTagList(ctx context.Context, arg GetArchiveByTagListParams) ([]GetArchiveByTagListRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveByTagList,
		arg.Uid,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveByTagListRow
	for rows.Next() {
		var i GetArchiveByTagListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.CoverPage,
			&i.Page,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByTag = `-- name: GetArchiveIDsByTag :many
;

select archive.id
from archive
join archive_tag on archive.id = archive_tag.archive_id
join tag on archive_tag.tag_id = tag.id
where tag.name = ?
`

func (q *Queries) GetArchiveIDsByTag(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveIDsByTag, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveIDsByTags = `-- name: GetArchiveIDsByTags :many
;

select archive.id
from archive
join archive_tag on archive.id = archive_tag.archive_id
join tag on archive_tag.tag_id = tag.id
where tag.name in (/*SLICE:tags*/?)
group by archive.id
having count(distinct tag.id) = ?2
`

type GetArchiveIDsByTagsParams struct {
	Tags   []string `json:"tags"`
	Amount int64    `json:"amount"`
}

func (q *Queries) GetArchiveIDsByTags(ctx context.Context, arg GetArchiveIDsByTagsParams) ([]string, error) {
	query := getArchiveIDsByTags
	var queryParams []interface{}
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Amount)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveTag = `-- name: GetArchiveTag :many
;

select tag.id, tag.name, tag.description, tag.count
from archive
join archive_tag on archive.id = archive_tag.archive_id
join tag on archive_tag.tag_id = tag.id
where archive.id = ?
`

func (q *Queries) GetArchiveTag(ctx context.Context, id string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveTag, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveTagIDs = `-- name: GetArchiveTagIDs :many
;

select tag.id
from archive
join archive_tag on archive.id = archive_tag.archive_id
join tag on archive_tag.tag_id = tag.id
where archive.id = ?
`

func (q *Queries) GetArchiveTagIDs(ctx context.Context, id string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveTagIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivesByTagName = `-- name: GetArchivesByTagName :many
;

select archive.id, archive.title, archive.summary, archive.language, archive.category, archive.page_count, archive.file_path, archive.file_size, archive.mod_time, archive.created_at, archive.updated_at, archive.release_date, archive.library_id, archive.phash_p0, archive.phash_p25, archive.phash_p50, archive.phash_p75, archive.cover_page, reading_progress.page, reading_progress.last_read, reading_progress.completed
from archive
join archive_tag on archive.id = archive_tag.archive_id
join tag on archive_tag.tag_id = tag.id
left join reading_progress on archive.id = reading_progress.archive_id and reading_progress.user_id = ?1
where tag.name = ?2
order by archive.title asc
limit ?4
offset ?3
`

type GetArchivesByTagNameParams struct {
	Uid    string `json:"uid"`
	Name   string `json:"name"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type GetArchivesByTagNameRow struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary"`
	Language    *string    `json:"language"`
	Category    *string    `json:"category"`
	PageCount   int64      `json:"page_count"`
	FilePath    string     `json:"file_path"`
	FileSize    int64      `json:"file_size"`
	ModTime     time.Time  `json:"mod_time"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ReleaseDate *time.Time `json:"release_date"`
	LibraryID   string     `json:"library_id"`
	PhashP0     *int64     `json:"phash_p0"`
	PhashP25    *int64     `json:"phash_p25"`
	PhashP50    *int64     `json:"phash_p50"`
	PhashP75    *int64     `json:"phash_p75"`
	CoverPage   int64      `json:"cover_page"`
	Page        *int64     `json:"page"`
	LastRead    *time.Time `json:"last_read"`
	Completed   *bool      `json:"completed"`
}

func (q *Queries) GetArchivesByTagName(ctx context.Context, arg GetArchivesByTagNameParams) ([]GetArchivesByTagNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchivesByTagName,
		arg.Uid,
		arg.Name,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivesByTagNameRow
	for rows.Next() {
		var i GetArchivesByTagNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Language,
			&i.Category,
			&i.PageCount,
			&i.FilePath,
			&i.FileSize,
			&i.ModTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseDate,
			&i.LibraryID,
			&i.PhashP0,
			&i.PhashP25,
			&i.PhashP50,
			&i.PhashP75,
			&i.CoverPage,
			&i.Page,
			&i.LastRead,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
;

select id, name, description, count
from tag
where name = ?
`

func (q *Queries) GetTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Count,
	)
	return i, err
}

const getTagList = `-- name: GetTagList :many
;

select id, name, description, count
from tag
order by name
limit ?
offset ?
`

type GetTagListParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) GetTagList(ctx context.Context, arg GetTagListParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementTagCount = `-- name: IncrementTagCount :exec
;

update tag
set count = count + 1
where id in (/*SLICE:tags*/?)
`

func (q *Queries) IncrementTagCount(ctx context.Context, tags []int64) error {
	query := incrementTagCount
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const removeTagFromArchive = `-- name: RemoveTagFromArchive :exec
;

delete from archive_tag
where archive_id = ? and tag_id in (/*SLICE:tags*/?)
`

type RemoveTagFromArchiveParams struct {
	ArchiveID *string  `json:"archive_id"`
	Tags      []*int64 `json:"tags"`
}

func (q *Queries) RemoveTagFromArchive(ctx context.Context, arg RemoveTagFromArchiveParams) error {
	query := removeTagFromArchive
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ArchiveID)
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const tagExists = `-- name: TagExists :execresult
;

select id, name
from tag
where name = ?
`

func (q *Queries) TagExists(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, tagExists, name)
}

const totalArchiveWithTag = `-- name: TotalArchiveWithTag :one
;

select count(archive.id)
from archive
join archive_tag on archive.id = archive_tag.archive_id
join tag on archive_tag.tag_id = tag.id
where tag.name = ?
`

func (q *Queries) TotalArchiveWithTag(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalArchiveWithTag, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateTagDescription = `-- name: UpdateTagDescription :exec
;

update tag
set description = ?
where id = ?
`

type UpdateTagDescriptionParams struct {
	Description *string `json:"description"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateTagDescription(ctx context.Context, arg UpdateTagDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateTagDescription, arg.Description, arg.ID)
	return err
}
