// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: url.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const archiveUrlExists = `-- name: ArchiveUrlExists :execresult
;

select url
from archive_url
where url = ?
`

func (q *Queries) ArchiveUrlExists(ctx context.Context, url string) (sql.Result, error) {
	return q.db.ExecContext(ctx, archiveUrlExists, url)
}

const bulkAddArchiveURLs = `-- name: BulkAddArchiveURLs :exec
;

insert into archive_url (archive_id, url)
select ?, value from json_each(?2)
`

type BulkAddArchiveURLsParams struct {
	ArchiveID string      `json:"archive_id"`
	Urls      interface{} `json:"urls"`
}

func (q *Queries) BulkAddArchiveURLs(ctx context.Context, arg BulkAddArchiveURLsParams) error {
	_, err := q.db.ExecContext(ctx, bulkAddArchiveURLs, arg.ArchiveID, arg.Urls)
	return err
}

const createArchiveURL = `-- name: CreateArchiveURL :exec
insert into archive_url (url, archive_id)
values (?, ?)
`

type CreateArchiveURLParams struct {
	Url       string `json:"url"`
	ArchiveID string `json:"archive_id"`
}

func (q *Queries) CreateArchiveURL(ctx context.Context, arg CreateArchiveURLParams) error {
	_, err := q.db.ExecContext(ctx, createArchiveURL, arg.Url, arg.ArchiveID)
	return err
}

const getArchiveUrlIDs = `-- name: GetArchiveUrlIDs :many
;

select id
from archive_url
where archive_id = ?
`

func (q *Queries) GetArchiveUrlIDs(ctx context.Context, archiveID string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveUrlIDs, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchiveUrls = `-- name: GetArchiveUrls :many
;

select id, url
from archive_url
where archive_id = ?
`

type GetArchiveUrlsRow struct {
	ID  int64  `json:"id"`
	Url string `json:"url"`
}

func (q *Queries) GetArchiveUrls(ctx context.Context, archiveID string) ([]GetArchiveUrlsRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchiveUrls, archiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchiveUrlsRow
	for rows.Next() {
		var i GetArchiveUrlsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArchiveUrl = `-- name: RemoveArchiveUrl :exec
;

delete from archive_url
where archive_id = ? and url in (/*SLICE:urls*/?)
`

type RemoveArchiveUrlParams struct {
	ArchiveID string   `json:"archive_id"`
	Urls      []string `json:"urls"`
}

func (q *Queries) RemoveArchiveUrl(ctx context.Context, arg RemoveArchiveUrlParams) error {
	query := removeArchiveUrl
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ArchiveID)
	if len(arg.Urls) > 0 {
		for _, v := range arg.Urls {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:urls*/?", strings.Repeat(",?", len(arg.Urls))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:urls*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
